### ISSUE TITLE
Fix statefulset labelling issue

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#105]
**Describe the issue**
There is PR specific label included in patroni statefulset, which cause the db to redeploy every new PR even though there is no db changes.

**Additional context**
https://github.com/bcgov/ocp-sso/blob/master/.pipeline/lib/deploy.js#L105

**Definition of done**
- remove the specific PR label from statefulset
- test on sandbox instance

**Comment by patricksimonian** [comment]
just need to sync up with @ShellyXueHan we are blocked o quota limits for sandbox instance due to other load testing sandbox instances.

**Comment by ShellyXueHan** [comment]
Update:
this fix is completed as of Nov 30
