### ISSUE TITLE
Redhat SSO 7.4 Upgrade

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/ocp-sso#107]
## Summary

Redhat SSO 7.4 is available. 

Upgrade Docs: https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.4/html/upgrading_guide/index
Change Log: https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.4/html/upgrading_guide/release_changes#rh_sso_7_4

**Comment by ShellyXueHan** [comment]
@patricksimonian we are on SSO 7.4. What is this ticket for specifically?

**Comment by ShellyXueHan** [comment]
https://access.redhat.com/errata/RHSA-2020:5254?sc_cid=701600000006NHXAA2

**Comment by brycereid73** [comment]
Use this epic for tasks related to patches, etc.
