### ISSUE TITLE
Duplicated login page for GitHub

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#11]
In test and prod SSO login page, when user pick GitHub idp, they are redirected to a second blue page with the GitHub button.

Steps to reproduce:
1. login with test/prod sso, try https://reggie-web-static-prod-devhub-prod.pathfinder.gov.bc.ca/?intention=LOGIN#error=login_required
2. Click on GitHub, this identifies the idp to be GitHub (using kcIDPHint)
3. user will be directed to a second sso blue page with a GitHub button

Expected:
step 3 should go to the GitHub login modal directly

**Comment by cvarjao** [comment]
Setup Default Identity Provider as documented:
https://www.keycloak.org/docs/3.4/server_admin/index.html#default_identity_provider

**Comment by cvarjao** [comment]
FYI, @ll911
