### ISSUE TITLE
Explore RHSSO operator

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#115]
**Describe the issue**
https://access.redhat.com/errata/RHEA-2020:4934?sc_cid=701600000006NHXAA2

**Definition of done**
- explore and see if applicable on our instances

**Comment by brycereid73** [comment]
More control on the resources

**Comment by zsamji** [comment]
@arcshiftsolutions thoughts if this issue is still needed?

**Comment by arcshiftsolutions** [comment]
@zsamji - I think we're ok with what we have in this case; our latest change in Uptime Robot should give us the result we want. We can explore it in the future if needed.
