### ISSUE TITLE
Monitoring for extra SSO metrics

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#117]
**Describe the issue**
the endpoint `http://localhost:9990/metrics` provides a lot useful metrics for sso pods, such as GC status... We can consider exporting that to prometheus or sysdig directly to better monitor sso.

**Additional context**
Might need a separate instance instead of enabling it cluster wide.

**Definition of done**
- explore possibilities

**Comment by stewartshea** [comment]
Some of these may already be collected by Sysdig; for instance, the JVM
stats are automatically displayed. In other cases, we may need to
specifically configure sysdig to pull some specific prometheus metrics

[image: image.png]

**Comment by ShellyXueHan** [comment]
Thanks @stewartshea ! Just created one with the JVM template and got similar dashboard as yours: https://app.sysdigcloud.com/#/dashboards/220482?last=3600&scope=kubernetes.namespace.name%20%3D%20%3F%22devops-sso-prod%22%20and%20kubernetes.pod.label.deploymentConfig%20in%20%28%22sso-prod%22%29

 I'll get some recommendation on useful stats from redhat and see if we can grab them.

**Comment by ShellyXueHan** [comment]
not using the JVM dashboard now. But if need to enable later on, could create one from sysdig -> dashboard -> application -> JVM. @nvunnamm @ConradBoydElliottGustafson
