### ISSUE TITLE
Custom Service Message when SSO is degraded

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/ocp-sso#119]
**Describe the issue**
When the SSO service experiences disruption clients will receive the 'application not available' message. 

**Task**

Find a better way of providing comms to our clients that the SSO Service is undergoing recovery so that they stop trying to hit the endpoints as much. 

**Implementation Details**

- This will firstly require a static site server that will redirect all SSO endpoint requests to a root html page
- there needs to be automation to switch the oidc routes from the sso service to the maintenance page service
- there needs to be automation to switch back to the sso service when available
- we need to decide when its worth it to do a 100% switch over because sometimes 25% of sso requests do work during degredation

**Comment by zsamji** [comment]
captured as backlog item
