### ISSUE TITLE
Add recommended EAP tuning to RH SSO based on Redhat's detailed summary report

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/ocp-sso#126]
# Summary

Redhat has completed their architecture review and have drawn some conclusions on what measures we can take to improve service reliability. 

## Todo

- apply the EAP level tuning to our SSO instance

## DoD

-  documented in the infrastructure code and reviewed

**Comment by patricksimonian** [comment]
waiting on detailed report from RH to see if any further tuning is required

**Comment by patricksimonian** [comment]
The short term recommendations from RH is:
- Resource allocation
- Replicate distributed cache
- Performance tuning


## Resource Allocation

At this stage we have already scaled the resource utilization to the most it can be given the current quota in 3.11. The app has been behaving well and based on profiling from sysdig + k6, we are seeing a decent utilization of our resource requests and limits. 

Because there is no way right now (see the k6 sysdig issue) to store historical metric information, we are not going to attempt to tune resource resources/limits further ( we would have no good way of verifying how effective our changes would be).

## Replicate distributed cache

Based on Shelly's investigation, it looks like we are already using replicated cache and it is behaving as expected [#116](https://github.com/bcgov/ocp-sso/issues/116)

## Performance Tuning

I've read the EAP tuning guide and it looks like based on our current utilization we should NOT perform any custom tuning to the EAP server for GC or the HEAP. We are constrained by our quota in 3.11 and therefor tuning GC and or the heap will likely cause a loss of performance in other threads of the SSO runtime.




## TODO

based on our current service, we need to evaluate its limit (using k6) to find out an intial service level.

**Comment by ConradBoydElliottGustafson** [comment]
@patricksimonian I can't tell by looking at this ticket why it was closed. I'm a ZenHub noob, but what is the actual state?
