### ISSUE TITLE
Confer with New SSO team to discuss maintenance pipeline tech and implementation

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/ocp-sso#127]
## Summary

With our current pipeline, it is challenging to do simple maintenance tasks. The pipeline-cli does have some pitfalls in that it builds/deploys al components at the same time. 

## Definition of Done

- schedule a meeting with new SSO team to discuss this problem and provide our planned solutions
- see if our planned solutions align with their tech skillset
- document our maintenance pipeline

**Comment by patricksimonian** [comment]
So Conrad and I have had a chat but i found that they are the new SSO team has yet to procure a team! 

Conrad liked our direction with moving towards a kubernetes native pipeline in silver as well as working directly with a lower level api to openshift for the time being. 

No formal docs have been made. I'll make a doc in ocp wiki to chat about the maintenance pipeline..

**Comment by ConradBoydElliottGustafson** [comment]
We have a team (OK 1 person -- but he's ready to rock).

**Comment by ConradBoydElliottGustafson** [comment]
@nvunnamm

**Comment by ShellyXueHan** [comment]
nice! let's get some onboarding done and rock the ship! (is that the term ppl use?)

**Comment by patricksimonian** [comment]
We're going to invite you guys to the sprint planning next just so can see our planned work for the next sprint which is going to be the OCP 4 migration!

**Comment by patricksimonian** [comment]
meeting setup!

**Comment by patricksimonian** [comment]
Meeting finished!
