### ISSUE TITLE
Implement a maintenance pipeline for changes to infrastructure for RH SSO 

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/ocp-sso#128]
# Summary

As described in the previous issue ( #127 ), there are challenges with the current pipeline to scheduling maintenance tasks which end up requiring manual overhead. 

## To do

- based on the outcome of issue #127 , implement the pipeline solution

## Definition of Done
- keycloak service can be brought down and back up automatically for maintenance :)

**Comment by ShellyXueHan** [comment]
As we shift focus to ocp4 migration, will visit this later on.

**Comment by zsamji** [comment]
captured in current sprint Oct 13-27 as Ops Stability
