### ISSUE TITLE
provision redhat sso namespaces in silver

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/ocp-sso#131]
## Summary 

In prep for SSO migration to silver, we need namespaces

## To Do

- provisioning request made
- yaml infra code of rolebindings to template
- (we should probs consider documenting the idea of gitopsifying rolebinding control via argo)

**Comment by ShellyXueHan** [comment]
### Update:
- currently waiting for project set provisioning to be complete
- we can't get a project set of 5. As for ocp4, we can only get standard project set with 4 namespaces. Manual namespace creation has been disabled. As a result, the team has suggested to make another project set request for sso sandbox. We will have to setup cicd pipeline to link up to the one extra when done

**Comment by ShellyXueHan** [comment]
### Update:
Namespaces here:
```
3d5c3f-dev - Single Signon Sandbox (dev)
3d5c3f-prod - Single Signon Sandbox (prod)
3d5c3f-test - Single Signon Sandbox (test)
3d5c3f-tools - Single Signon Sandbox (tools)

6d70e7-dev - Single Signon (dev)
6d70e7-prod - Single Signon (prod)
6d70e7-test - Single Signon (test)
6d70e7-tools - Single Signon (tools)
```

Also need a quota increase of SSO OCP4 project sets to Medium:
1 SSO instance will need:
- 7 cores - 14 cores
- 7 GiB - 14 GiB

1 DB instance will need:
- 750 millicores to 1500 millicores
- 3 GiB to 6 GiB

Audit log backup process will need:
- 50 millicores to 250 millicores
- 256 MiB to 1 GiB

**Comment by ShellyXueHan** [comment]
dup of https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/ocp-sso/131

closing
