### ISSUE TITLE
OCP4 Migration - Quota Increases

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/ocp-sso#140]
**Describe the issue**
The SSO service requires a lot of CPU, Memory, and Storage. Far more than the silver small size allows. We will need to upgrade our quotas to fit our resource requirements

## To Do
- find out how much CPU, Memory, and Storage we will need at a minumum
- make a quota increase request to get said quota
-
**Definition of done**
- project set has the appropriate quota increase to satisfy our resource consumption requirements

**Comment by ShellyXueHan** [comment]
### Update:
Namespaces here:
```
3d5c3f-dev - Single Signon Sandbox (dev)
3d5c3f-prod - Single Signon Sandbox (prod)
3d5c3f-test - Single Signon Sandbox (test)
3d5c3f-tools - Single Signon Sandbox (tools)

6d70e7-dev - Single Signon (dev)
6d70e7-prod - Single Signon (prod)
6d70e7-test - Single Signon (test)
6d70e7-tools - Single Signon (tools)
```

Also need a quota increase of SSO OCP4 project sets to Medium:
1 SSO instance will need:
- 7 cores - 14 cores
- 7 GiB - 14 GiB

1 DB instance will need:
- 750 millicores to 1500 millicores
- 3 GiB to 6 GiB

Audit log backup process will need:
- 50 millicores to 250 millicores
- 256 MiB to 1 GiB

**Comment by ShellyXueHan** [comment]
dup of https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/ocp-sso/131

closing

**Comment by ShellyXueHan** [comment]
### Update:

Both project set now has medium quota.
