### ISSUE TITLE
OCP4 Migration - Dev DNS change

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/ocp-sso#141]
**Describe the issue**
Update our DNS names to resolve to the silver cluster

**Additional context**
You can run `nslookup` against an app hosted on silver to find what the ip we need our DNS to resolve too.

**Definition of done**
DNS resolution updated to resolve to silver for dev.oidc.gov.bc.ca

**Comment by ShellyXueHan** [comment]
### Update:
pro tip from Jason:
the current TTL are set to 1200s (20 mins). make sure before we repoint the DNS, change this to shorter time like 1 min. "So do the TTL at least 20min before the change you are fine. It will just help systems pickup the change in IP address faster." Afterwards, change it back.
