### ISSUE TITLE
SBC Realm IDIR mapper issue

### ISSUE THREAD

**Issue by JohnamLane** [bcgov/ocp-sso#15]
IDIR accounts in SBC's TEST and PROD environments are not being mapped to the keycloak user profile as expected. 
Username and email are correct
But, Last name is blank and first name is actually "last, first CITZ:EX"

It's my understanding that our team has not changed any mapper settings.

Please let me know if you need any other details.

**Comment by cvarjao** [comment]
@JohnamLane , that is as expected. We really wish there was only `displayName`, so it was decided that `last name` would NOT be used, and `first name` would have the `displayName`. We are reviewing that decision, and we may provide `first name` and `last name` when available.

**Comment by cvarjao** [comment]
@JohnamLane, closing as duplication. please vote/follow #30 and/or #31.
