### ISSUE TITLE
SSO does not support user attribute with special character 

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#151]
**Describe the issue**
User names with special character does not display and will be changed into unknow symbols.

**Additional context**
RC chat: https://chat.developer.gov.bc.ca/channel/devops-ocp4-migration?msg=DsK3XffSos6L9eR49

**Definition of done**
- investigate into the issue and see if it's version specific
- plan for fixing

**Comment by arcshiftsolutions** [comment]
This item is still an issue. More info on a possible solution: https://access.redhat.com/solutions/4560101

**Comment by zsamji** [comment]
no clients have complained since August 2021
