### ISSUE TITLE
OCP4 Migration - Migrate operational components

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#152]
**Describe the issue**
after migrating the pipeline, we will also need to migrate the other ops components and data, in all environments:
- [x] backup container (helm chart version)
- [x] audit log backup (done as part of sso initial migration)
- [x] k6 testing (tested in ocp4 sandbox)
- [x] keycloak admin scripts (also tested in ocp4 sandbox)
- [x] update RC webhook URLs from pathfinder to developer! (Sysdig, backup container and audit log backups notifications)

**Definition of done**
- components spin up in ocp4 and data migrated

**Comment by patricksimonian** [comment]
are the RC webhook urls only in sysdig?

**Comment by patricksimonian** [comment]
sysdig webhook adjusted
