### ISSUE TITLE
Jenkins Pipeline - Need better output for jenkins skipping cicd job

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#157]
**Describe the issue**
Jenkins will only start build when:
- it's triggered by GitHub PR changes
- AND there are file changes in the following dir: `^docker\`, `^extensions/`, `^openshift/sso*`, `^.pipeline/`

If not, then it will error out and terminate the current job. See the jenkins file for details: https://github.com/bcgov/ocp-sso/blob/master/Jenkinsfile#L16-L23

However, this situation we will not be able to see the error logs in time but only sees a failed job. So better job termination is needed which should quit with a message but without error.

**Definition of done**
- update jenkinsfile to terminate job without error

**Comment by zsamji** [comment]
team established jenkins not needed for keycloak deployment. using helm
