### ISSUE TITLE
OCP4 Migration version incompatability 

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/ocp-sso#169]
**Describe the issue**
The SSO Service is migrating from ocp 3 to ocp 4. With that it appears the version cahnges from 7.4.2GA to 7.4.4 GA
This may cause issues with java clients that are using the keycloak 7.4.2GA library.

**Fix**

Upgrade your keycloak java library to the 7.4.2 version

**Comment by ShellyXueHan** [comment]
RedHat Container image is missing SSO image at 7.4.2.GA. Support ticket created: https://access.redhat.com/support/cases/#/case/02858147

**Comment by ShellyXueHan** [comment]
### Updates:
Got the reference for 7.4.2.GA image: https://access.redhat.com/containers/#/registry.access.redhat.com/rh-sso-7/sso74-openshift-rhel8/images/7.4-4

we would redeploy sso-dev to use the old one anytime. Just need to retag it in -tools.

**Comment by ShellyXueHan** [comment]
So far there are two issues found with the version update and are resolved. Closing ticket since we are going to continue with new version.
