### ISSUE TITLE
Unresolvable Validation Errors Prevents Update of User Details 

### ISSUE THREAD

**Issue by amichard** [bcgov/ocp-sso#17]
![screen shot 2019-03-07 at 9 51 11 am](https://user-images.githubusercontent.com/12942893/53987242-4e74cd00-40d5-11e9-9dec-33d5c1c444e4.png)

As seen in the screenshot, I'm getting a Missing or invalid field(s) error. But none of the fields are marked in red. So the message doesn't really tell me what information I'm missing. 

I was trying to add my lat name in the details. 

I was told that it might be caused by the ```\``` in the Username field, but since that can't be edited, I don't know how to resolve it.

**Comment by ShellyXueHan** [comment]
You can edit the username mapper in the IDPs![Screen Shot 2019-03-22 at 1.09.16 PM.png](https://images.zenhubusercontent.com/5c1acc79305b926f81e2c3d4/e7d893df-3a4a-414d-8302-8b713d4f4d8b)

**Comment by amichard** [comment]
If I change the mapper in the IDPs, does that affect the existing users?

If not, the users with "\" on their username will still fail edits. Is there a way around this outside of writing a function through an API?

**Comment by ShellyXueHan** [comment]
After changing the mapper, the username will be updated the next time user login through that idp. But it is still the same account in the realm.

Why could you have users with "" as the username? You could try the keycloak api to update user profile.

**Comment by amichard** [comment]
Oh, the escape didn't go through properly. That was supposed to be a backslash \

So the only way to update is through the API and not through the UI?

**Comment by cvarjao** [comment]
Change the mapped to a different one. New realms are now using `${CLAIM.preferred_username}@${ALIAS}` format, and we are no longer recommending `${ALIAS}\${CLAIM.preferred_username}`

You may also use whichever character you want as separator. Some teams prefers ``${ALIAS}_${CLAIM.preferred_username}`
