### ISSUE TITLE
SSO 7.4.4.GA FAQs

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#172]
### Background:
We are in the progress of rolling SSO from `7.4.2.GA` to `7.4.4.GA`. There are several security patches and some might affect your app integration. Here are some things that teams have spotted.

### 1. refresh_token is gone
The OAuth2 Client Credentials Grant endpoint does not issue refresh tokens by default. This behavior is aligned with the OAuth2 specification. As a side-effect of this change, no user session is created on the RH-SSO server side after successful Client Credentials authentication, which results in improved performance and memory consumption.

If you need to keep the behavior of old RH-SSO versions (aka, RH-SSO 7.3.3 and earlier), then it can be enabled for the particular client in the RH-SSO admin console, in client details, in the section with `OpenID Connect Compatibility Modes` with the switch `Use Refresh Tokens For Client Credentials Grant`. This will allow you to still generate a refresh token in the access token response.

### 2. my Camunda integratio doesn't work!
You'll need to update the JAVA package to match the new version from 1.5 to 2.1

```<groupId>org.camunda.bpm.extension.examples</groupId>
<artifactId>camunda-bpm-identity-keycloak-examples-sso-kubernetes</artifactId>
<version>2.1.0-SNAPSHOT</version>
```

**Comment by loneil** [comment]
Note the `Use Refresh Tokens For Client Credentials Grant` setting does not seem to appear in advance until the upgrade happens (ie, I can see it in Dev right now but not Test) so if setting you'll have to do it in conjunction with the update once the new console is there.

**Comment by zsamji** [comment]
will create new FAQ if questions arise after our 7.4.9 upgrade
