### ISSUE TITLE
Personal BCeID SAML payload no longer contains the email address

### ISSUE THREAD

**Issue by arcshiftsolutions** [bcgov/ocp-sso#173]
# What's the issue?
Logging into BCeID via an app realm on SSO with a Personal BCeID; the SAML payload no longer contains the email address. 

# Sample SAML Payload
The following payload is from a login with a Personal BCeID. Note the email attribute is missing. We've noted this with several users which have confirmed email addresses. 

```
<ns2:AttributeStatement>
	<ns2:Attribute Name="username" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
		<ns2:AttributeValue>SOME_PERSONAL_BCEID</ns2:AttributeValue>
	</ns2:Attribute>
	<ns2:Attribute Name="email"
                   NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
                   >
		<ns2:AttributeValue/>
	</ns2:Attribute>
	<ns2:Attribute Name="firstname"
                   NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
                   >
		<ns2:AttributeValue/>
	</ns2:Attribute>
	<ns2:Attribute Name="lastname"
                   NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
                   >
		<ns2:AttributeValue/>
	</ns2:Attribute>
	<ns2:Attribute Name="displayname"
                   NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
                   >
		<ns2:AttributeValue>John Wayne</ns2:AttributeValue>
	</ns2:Attribute>
	<ns2:Attribute Name="useridentifier"
                   NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
                   >
		<ns2:AttributeValue>ABCGUID</ns2:AttributeValue>
	</ns2:Attribute>
	<ns2:Attribute Name="SMGOV_BUSINESSGUID"
                   NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
                   >
		<ns2:AttributeValue>Individuals</ns2:AttributeValue>
	</ns2:Attribute>
</ns2:AttributeStatement>
```
## Impact
Some teams are having issues with these users since their app realms use the `Login with email` setting. 

## Possible Solution
Ask the WAM team to look into the configuration for Personal BCeID (for SSO).

**Comment by GregFPoirier** [comment]
Can I get and update on this issue?

**Comment by arcshiftsolutions** [comment]
Hi @ShellyXueHan - have you received any updates from WAM on this issue?

**Comment by ShellyXueHan** [comment]
Currently waiting for WAM team availability to start debugging.

**Comment by arcshiftsolutions** [comment]
@GregFPoirier - We had a session with WAM on Friday and they've confirmed there's an issue. They're looking at it and will let us know when there's a resolution. We'll report back as soon as we have more info.

**Comment by arcshiftsolutions** [comment]
@GregFPoirier - As discussed, we have created a FAQ for this in the OCP-SSO repo. 

[Link to FAQ](https://github.com/bcgov/ocp-sso/issues/185)

Closing this issue.
