### ISSUE TITLE
Allow teams to access their audit logs

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/ocp-sso#177]
**Describe the issue**
Sometimes teams require audit logs to debug client issues or configurations. Currently this is a manual process of a sso administrator (edit access or higher) to query the logs

**Additional context**
There are scripts found here https://github.com/BCDevOps/keycloak-admin/tree/master/log-query-tool that currently accomplish on pulling logs for a teams realm

**Definition of done**
- a secure self-serve way for teams to access their audit logs

**Comment by seeker25** [comment]
This would be very useful, we have some clients that are getting:

![image](https://user-images.githubusercontent.com/3484109/108543688-3edaf880-729a-11eb-9f4d-46840a15d184.png)

Having the logs would help a ton.

**Comment by zsamji** [comment]
revisit as arises from client engagements
