### ISSUE TITLE
SSO Production service degradation 

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#179]
### What happened:
We had several 10mins long service degradation as of Feb 8th 9:40 - 11:00 where SSO service returns "Application not available" and timeouts. This issue might be a result of several events coupled together, ocp3 node patching and unexpected/abnormal SSO usage and network traffic increase.

### Investigation:

***On SSO side:***

It has HPA setup to scale from 5 to 7 pods when CPU hits 80% limit. However, this does not help much as sso pods are not quick spin-up pods (it takes 2-3 minutes to get ready). Also when SSO pods are generally busy, new pods failed to sync up status with the existing ones. For example, error message:
```
18:39:40,680 ERROR [org.infinispan.interceptors.impl.InvocationContextInterceptor] (timeout-thread--p10-t1) ISPN000136: Error executing command PutKeyValueCommand on Cache 'sessions', writing keys [fb22a7cd-b4c2-4382-bafe-643100cb47dc]: org.infinispan.util.concurrent.TimeoutException: ISPN000476: Timed out waiting for responses for request 7991 from sso-prod-1-4xv4f
	at org.infinispan@9.4.19.Final-redhat-00001//org.infinispan.remoting.transport.impl.MultiTargetRequest.onTimeout(MultiTargetRequest.java:167)
	at org.infinispan@9.4.19.Final-redhat-00001//org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:87)
	at org.infinispan@9.4.19.Final-redhat-00001//org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:22)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

***On DB side:***
There are node patching activity happening in the morning that cause some failover. In addition, primary DB pod is all time over CPU limit (0.5 cores limit vs. 0.58-0.6 cores usage) that also cause DB connection timeout for SSO pods, further leading to frequent SSO pod kill.

***Abnormal SSO network traffic:***

We have also noticed 3x to 15x the normal amount of network traffic to the sso service this morning, which is pointing to some apps' increasing load/sso usage.

### Potential Fixes:

***On SSO side:***
Remove HPA for now and leave it at 7 pods.
Or consider cronjob to increase replicas during busy hours (8-6) and scale backdown during evenings/weekends, based on what network traffic we are observing now on sso. However, this is only prediction for general sso usage, not for any specific apps using sso. To be on the safe side, consider having 7 pods (or # pods that satisfy busy usage) running all time.

***On DB side:***
Option A: Leave things alone and let the database recover and sso pods to recover (this leads to a service degredation for an unknown amount of time)

Option B: Update DB statefulset with increased CPU and memory requests. This will lead to a service down time for approximately 10ish minutes

***Abnormal SSO network traffic:***
Looking into audit logs to identify what are the abnormal/heavy events happened this morning. Once narrow down, communicate with teams.

**Comment by nvunnamm** [comment]
Looks like there is a solution in redhat customer portal with the same issue..
https://access.redhat.com/solutions/3617211
Am not able to view the solution as am not an active subscriber. Do we have any active subscription that I can use?

**Comment by brycereid73** [comment]
Need to create redhat account then ask Olena to invite into the support center. Shelly suggests creating one account for the team.

**Comment by patricksimonian** [comment]
It had turned out that an applicatoin team was misusing the kc api. THey were doing rapid introspection calls which is an expensive process. 

We found the team in question by checking the Audit logs and correlating them with the network traffic spikes. 

The logs showed a pattern of many introspection calls.

## Remediation

After chatting with the team we found they were using a python oidc library that did not follow oidc best practices (caching tokens, discovery etc). When they updated the library our network issues were resolved.
