### ISSUE TITLE
Better analytics of event logs

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/ocp-sso#181]
We've encountered an issue where an excessive amount of INTROSPECTION calls were made to the service. This particular call is resource intensive and resulted in service degradation. 

There should be a way to keep track of these calls as they come to create alerts or some other form of automation. Ideally this will help us identify clients that are misbehaving so that we can reliably offer our service.

**Comment by zsamji** [comment]
removed  introspection. will revisit as needed by clients
