### ISSUE TITLE
Custom role mapper authenticator not able to detect empty fields

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#184]
**Describe the issue**
We have a custom built extension `RequireRoleByClient` https://github.com/bcgov/ocp-sso/blob/master/extensions/services/src/main/java/com/github/bcgov/keycloak/authenticators/RequireRoleByClient.java

It requires filling in config for it to work, ow an empty execution will result in errors like this:
```
[0m [33m21:44:40,256 WARN  [org.keycloak.services] (default task-3424) KC-SERVICES0013: Failed authentication: java.lang.NullPointerException
	at deployment.bcgov-services-1.0.0.jar//com.github.bcgov.keycloak.authenticators.RequireRoleByClient.authenticate(RequireRoleByClient.java:60)
```

However, by default when the execution is created it's left empty and there's no warning for that.

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

- [ ] check with RedHat to see if that's something would be improved from keycloak side
- [ ] if not, update the extension to check for valid and required fields

**Comment by zsamji** [comment]
have not heard this an issue. will revisit if it is
