### ISSUE TITLE
Personal BCeIDs logging into SSO do not contain their email address

### ISSUE THREAD

**Issue by arcshiftsolutions** [bcgov/ocp-sso#185]
# What's the issue?
Personal BCeID SAML payloads do not contain the email address while logging into SSO.

## How do I know if I have the issue?
If your application has users which are logging in with a **Personal BCeID** and presented with an error message similar to this issue: [OCP-SSO 68](https://github.com/bcgov/ocp-sso/issues/68). Issue **does not impact** basic or business BCeID users.

## Why are emails not being passed?
We have met with the WAM team and they have provided the following:

> It appears to be by design. Back in 2009 when Personal BCeID was introduced it was decided that in order to ensure protection of personal information for personal BCeID PI such as email addresses, first name and last name would not be populated in BCeID’s Active Directory. If an application required those attributes they had to make web service calls to BCeID directly.  

## What do I do if my realm has an issue?
As recommended in [ocp-sso issue 68](https://github.com/bcgov/ocp-sso/issues/68):

- Ask a realm admin to change the following login settings:
- `Realm Settings` -> `Login tab` -> `Login with Email` -> set to `false`
- `Duplicate Emails` -> set to `true`

**Comment by zsamji** [comment]
Moving to closed as personal bceid is no longer offered
