### ISSUE TITLE
Experiencing intermittent gateway timeout issues in sso

### ISSUE THREAD

**Issue by nvunnamm** [bcgov/ocp-sso#192]
**Describe the issue**
Experiencing intermittent gateway timeout issues in sso 
will use this issue for capturing logs for the affected realm that way we can cross-reference and look for patterns and solve this issue.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by brycereid73** [comment]
is this closed?

**Comment by ConradBoydElliottGustafson** [comment]
Not happening any more. The cause might have gone away.
