### ISSUE TITLE
Logging in with a Re-used Email Address in Multiple BCeID Accounts Shows an Incorrect Username/Password Error

### ISSUE THREAD

**Issue by amichard** [bcgov/ocp-sso#20]
![Screen Shot 2019-03-11 at 8 07 57 AM](https://user-images.githubusercontent.com/12942893/54134228-d0663e00-43d4-11e9-81af-77c26bc4a553.png)

We have some BCeID users that have multiple BCeID accounts and they share the same email address. So while I was testing this feature, we ran into an issue where we're receiving an "Invalid Username/Password" error.

**Comment by ShellyXueHan** [comment]
Duplicate emails is enable for BCeID in dev, test and prod SSO. @amichard could you confirm and close, thx!

**Comment by amichard** [comment]
Sorry @ShellyXueHan for the late reply.

Yes, this is fixed. Closing now.
