### ISSUE TITLE
Several users are running into the "User Already Exists" message; may have downstream impacts in time

### ISSUE THREAD

**Issue by arcshiftsolutions** [bcgov/ocp-sso#209]
**Describe the issue**
We continue to have IDIR users which run into the "user already exists" message while logging into Keycloak.

**Additional context**
https://github.com/BCDevOps/devops-requests/issues/939

> The IDIR in question was originally provisioned ~2 years ago. It has been recently re-enabled, but also transferred to another ministry's purview. Presumably, the IDIR was given a new UUID and now keycloak is prompting me to merge the profiles together. However, I do not have have access to the credentials associated with the original account.

**Definition of done**
Ideally we come up with a solution which eliminates this issue; we may need to involve IDIM however we could also look at our mapper setup to see if there's a way around this.

**Comment by arcshiftsolutions** [comment]
@brycereid73 FYI.

**Comment by brycereid73** [comment]
@var0101 We'll need to prioritize this work. I suggest we start targeting future sprints.

**Comment by zsamji** [comment]
@ConradBoydElliottGustafson what's our direction on this?

**Comment by ConradBoydElliottGustafson** [comment]
@zsamji This is a possible "future improvement". I added it as a card on Trello.
https://trello.com/c/BdIppwcs
