### ISSUE TITLE
Update the realm-o-matic to point to the Both Realm

### ISSUE THREAD

**Issue by brycereid73** [bcgov/ocp-sso#213]

**Comment by ConradBoydElliottGustafson** [comment]
@nvunnamm @Sandeeparch I found the line of code that needs to be changed: keycloak-admin/link-idp-realm.yml at master · BCDevOps/keycloak-admin (github.com) (line 11)

**Comment by Sandeeparch** [comment]
To Change realm-o-matic pointing to Both realm, the below components needs to be analyzed 
Front End - Node JS application
Back End - Playbooks
Database - Schema

The Ansible playbooks needs to be updated and new tasks has to be created.

Tasks Involved:
Understand the node js application & realm-o-matic
make the changes in local before proceeding to Dev/Test
