### ISSUE TITLE
Determine BCeID account type for each realm

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/ocp-sso#219]
Once the shared realms are up and running, we would like to start consolidating clients into the shared realms if they really don't need a dedicated realm. 

As part of this work we will need to figure out what "flavors" of BCeID are being used by the realms. In order to do THAT, we need to do a query for each user to the BCeID web service, passing the BCeID_userid to find out what kind of user each one of them is.

See conversation below:

Good Afternoon Marco,

A quick note – I know you were hoping for a response before your 3:00 PM meeting today.

In the future, you can ensure a more timely response by using our group monitored mailbox:  IDIM.Consulting@gov.bc.ca 

•	BCeID Web Services could certainly be used for what you have described below – You would need to document the new BCeID Web Service use cases, and we would need to add them to the Client signed Service Agreement we have with the DevExchange.

•	The only approval you need is to a) document the new BCeID web service call use cases + have them added to an updated Service Agreement and b) have Rob Lowe or I configure them in the BCeID application.
o	Emphasis needs to be given to enumerating the ‘Access Constraints’
o	We will send you a link to the data elements shared guide and our BCeID use cases template (separate email – likely from Rob Lowe)

•	The BCeID Client Manager for the existing KeyCloak (DIAMS) OSD entry under the Citizens’ Services Client profile is Garry Mierzuak.
o	Garry Mierzuak should be able to provide you with the OSID # (if unavailable, contact Rob Lowe or I)
•	The Service Agreement Administrator (signatory) for the existing KeyCloak (DIAMS) agreement was Todd Wilson.

Can you share the number of unique [User GUID] BCeID accounts there are in the KeyCloak identity store?
o	Based on that number of existing BCeID accounts using the DevExchange KeyCloak will help use refine the possibility of additional / supplementary / different account lookup alternatives.

Best Regards,

Tim McGuire
Client Onboarding Manager - BCeID
Provincial Identity Information Management – Service BC Division
Ministry of Citizens’ Services 
PO Box 9412, Stn B Prov Gov, Victoria BC V8W 9V1
Tim.McGuire@gov.bc.ca
250 507-7685
“Access to government services made easy” 
         

From: Villeneuve, Marco EDUC:EX <Marco.1.Villeneuve@gov.bc.ca> 
Sent: March 16, 2021 1:37 PM
To: McGuire, Tim CITZ:EX <Tim.McGuire@gov.bc.ca>
Cc: Han, Shelly CITZ:EX <Shelly.Han@gov.bc.ca>; Reid, Bryce <bryce.reid@cgi.com>; Vunnam, Niranchandra CITZ:IN <niranchandra.vunnam@cgi.com>; Gustafson, Conrad CITZ:IN <c.gustafson@cgi.com>; Simonian, Patrick CITZ:EX <Patrick.Simonian@gov.bc.ca>; Bommi Reddy, Sandeep Reddy <sandeepreddy.bommireddy@cgi.com>; Shankar, Vardhman CITZ:EX <Vardhman.Shankar@gov.bc.ca>
Subject: Web Service & OSID

Hi Tim,

The team is moving forward with our migration to segregated realms. As part of this work, we’re hoping to create a small script which will:

•	Pull the BCeID users from a specific realm
•	Make one web service call per user to the BCeID web service to determine the user type
•	We’ll compile these for each realm to give us an indication of which applications are using which type of BCeID
•	This will help us migrate teams to the new segregated realms

We have the BCeID web services guide (V2.10.0) and would like to ask the following:

•	Do we need further approval to use the web service in this way? 
•	We’re currently unsure who our BCeID admin is for the SSO integration – can you please advise?
•	When we determine the admin, they should be ok to login to BCeID.ca to determine our OSID? 

On another note, if there’s a more efficient way to accomplish what we’re looking to do here, please let us know. 😊

Thanks Tim – we’re happy to have a quick session if we need to discuss further.

Marco Villeneuve
Application Architect & DevOps Lead | Ministry of Education PEN Project
778-676-1622

**Comment by zsamji** [comment]
to revisit as part of shared client journey map
