### ISSUE TITLE
Define metrics

### ISSUE THREAD

**Issue by brycereid73** [bcgov/ocp-sso#237]
- Onboarding Times
- Response time for Incidents
- Resolution times for Requests and Incidents
- Number of incidents, requests

Outages 
- Mean time to recover
- Number of outages
- Number of failed health checks

Number of Client originating issues (Incidents)

Degradation:
- Average Request Response time
- Peak request response time
- Time below threshold (request response time)
- Normal = 10ms

Number of Realms
Number of Clients Apps
Contact info
- Name
- email
- phone number
- enhancement: back up contact
Purpose of application
Criticality (If possible request PIA information to determine this. From risk profile. )

As the Service Owner, I want to have detailed contact information for each user so that I can effective communicate 
Acceptance Criteria 
* business accessible 
* Purpose of their App
* Sector
* Email
* Name
* Phone
* City
* Volume of use
* Which IdP's they're integrated with
* Using roles?

**Comment by zsamji** [comment]
team meeting on metrics addresses strategy going forward
