### ISSUE TITLE
Access Token is invalided/lost after restart

### ISSUE THREAD

**Issue by cvarjao** [bcgov/ocp-sso#24]
When a pod gets killed, a logged user who has a valid and non-expired access token is unable to refresh the access token.

```
{"error":"invalid_grant","error_description":"Session not active"}
```

References:
https://stackoverflow.com/questions/50203490/keycloak-access-tokens-invalid-after-keycloak-server-restart

**Comment by cvarjao** [comment]
A support case has been opened with Red Hat: https://access.redhat.com/support/cases/#/case/02341105

**Comment by cvarjao** [comment]
RedHat suggests that we change the `distribute-cache` entries to be more than 1.
```xml
<distributed-cache name="sessions" mode="SYNC" owners="1"/>
<distributed-cache name="authenticationSessions" mode="SYNC" owners="1"/>
<distributed-cache name="offlineSessions" mode="SYNC" owners="1"/>
<distributed-cache name="clientSessions" mode="SYNC" owners="1"/>
<distributed-cache name="offlineClientSessions" mode="SYNC" owners="1"/>
<distributed-cache name="loginFailures" mode="SYNC" owners="1"/>
```

Waiting for further clarification in regards to which cache to update as well as recommended values.

**Comment by cvarjao** [comment]
Recommended configuration has been deployed to PROD as part of PR #26.

**Comment by gil0109** [comment]
Sorry this did not resolve my issue.

Error:  ```{"error":"invalid_grant","error_description":"Session doesn't have required client"}```
Response Header: ```Request URL: https://sso-test.pathfinder.gov.bc.ca/auth/realms/sbc/protocol/openid-connect/token
Request Method: POST
Status Code: 400 Bad Request
Remote Address: 142.34.208.209:443
Referrer Policy: no-referrer-when-downgrade````

**Comment by lukegonis** [comment]
@cvarjao any updates on this?

**Comment by cvarjao** [comment]
I believe, @gil0109 have switched to offline token as a workaround. Since he was testing for us, we will need to spend some time creating some test scenario to test this, and see if it get fixed with the new version or not.

**Comment by ShellyXueHan** [comment]
We are on sso version 9.4 now, need to double check if issue is resolved or not. Some more related info: https://access.redhat.com/support/cases/#/case/02713060

**Comment by zsamji** [comment]
This issue is expected as these tokens are stored in individual pod memory. We have not defined this as critical based on our observation since August 2021
