### ISSUE TITLE
Create the IDP client in the new "both" realm in sandbox (ANSIBLE)

### ISSUE THREAD

**Issue by brycereid73** [bcgov/ocp-sso#244]

**Comment by ConradBoydElliottGustafson** [comment]
Since we didn't request SiteMinder SAML configuration for the SandBox realm, we can create this but we can't test it.

**Comment by ConradBoydElliottGustafson** [comment]
This ticket was based on a misunderstanding. We don't need a client in the realm at this point. We create a client when we create a new child realm that wants to use the IDP realm for login. We would also create a client for a customer as part of "onboard-o-matic".
