### ISSUE TITLE
Logging out with BCeID then logging in with IDIR causes internal server error

### ISSUE THREAD

**Issue by stephenhillier** [bcgov/ocp-sso#27]
Steps to reproduce:

1. Log in with BCeID
2. Log out
3. Log in with IDIR
4. Error screen is displayed

This happened for me both on an SSO enabled app (GWELLS) and the SSO console GWELLS realm.

**Comment by cvarjao** [comment]
Related to #4

**Comment by cvarjao** [comment]
This is a known error. Please vote/follow #4
