### ISSUE TITLE
Identity Access Landscape Awareness

### ISSUE THREAD

**Issue by ravi-bhatnagar** [bcgov/ocp-sso#270]
---
# **User Story**
* **As** a potential new organizational user
* **I want to** understand the identity landscape (i.e. IDAM - Identity and Access Management) of the BC Government
* **So that**  I can choose the right solution to meet my organizational needs.

## **Acceptance Criteria or Constraints**
* I'll see this or
* The solution will conform to this or
* Non-functional requirements

### Scenario 1: xxxxxx
* GIVEN ... 
* WHEN ... 
* THEN ... 

### Scenario 2: xxxxxx
* GIVEN ... 
* WHEN ... 
* THEN ... 

## Dependencies? 
Team or ideally a ticket 

## Risks
Description | Impact | [Strategy](https://en.wikipedia.org/wiki/Risk_management#Potential_risk_treatments) | Contingency Plan
------------ | ------------- | ------------- | -------------
If this does or doesn't occur by... | Then this will happen, costing $? | Mitigate, Transfer, Accept, Avoid | We will do this, if it occurs
 | | |

----

# Process Guidance
### User Story
A short introductory section with the following structure:
**As a:** the person or role who will benefit from the feature;
**I want:** the feature;
**so that:** the benefit or value of the feature.

### Acceptance Tests or also called Behaviour Driven Development Acceptance criteria
A description of each specific scenario of the narrative with the following structure:
**Given:** the initial context at the beginning of the scenario, in one or more clauses;
**When:** the event that triggers the scenario;
**Then:** the expected outcome, in one or more clauses.

**Comment by zsamji** [comment]
addressed in current public facing pages
