### ISSUE TITLE
IDIR and BCeID accounts with missing (or empty) e-mail

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#28]
### Background:
IDIR issue:
- For IDIR accounts without an email, the email attribute shows as *an empty string* instead of `null` on keycloak. This only appears in production, not dev or test environments.

BCeID issue:
- some old BCeID accounts that do not contain an email attri
- BCeID accounts (which is registered with an email address) that show up on KeyCloak without email attri

### Check with your user first to confirm the IDIR/BCeID account has an email in the profile
- IDIR: ask user to either call 77000, or login to summer.gov.bc.ca, if Outlook could successfully load, then you could confirm user has email
- BCeID: verify at https://www.bceid.ca/profile_management/

### Solutions? Status? Help needed!
- We are still working with IDIM team to fix the IDIR inconsistency.
- We need more information to start the BCeID debugging with IDIM.
- If you can confirm user account has email but not populated in KeyCloak, please provide details in this ticket. If possible, please ask the specific users to capture the saml payload during log on. Detailed information is very helpful.

Thank you!

**Comment by nickmailhot** [comment]
BCeID Basic did not have mandatory email field until 2015. So basic BCeID made before this could have a blank email. For more questions please feel free to email IDIM.Consulting@gov.bc.ca

**Comment by amichard** [comment]
We encountered this twice recently with our PROD environment.

They're both Business BCEID accounts and we got reports that they couldn't log into the system (we use their email address to automatically map their accounts to keycloak).

They both have all their details filled in and we can't find anything that's jumping out on why their email address weren't automatically mapped in keycloak.

**Comment by wenzowski** [comment]
I don't have a borked BCeID to test this with, so please forgive my ignorance: shouldn't a `First Login Flow` like `first broker login` assigned to the identity provider handle this at a Keycloak level?

**Comment by ShellyXueHan** [comment]
We've done a quick debugging. There is no email attribute populated even on BCeID realm level so there's nothing to be passed to the application realm. Further debugging will need IDIM team's collaboration.

@wenzowski However, as a temporary fix, @amichard could use the `first broker login` flow to enable user profile review. So that empty fields could be filled by users manually. Details to come depending on Richard's tests.

**Comment by mmumby** [comment]
We've encountered an issue with a BCeID user, she has two BCeID's (basic and personal) both using the same email address. She is unable to merge the two, so as a remedy we have enabled "Duplicate emails" on our MDS realm. 

Through our debugging process, we have removed her account from Redhat and had her re-authenticate thus creating a new user. 

The email field is no longer populating with her email from her personal BCeID. Note, I have deleted her account in the past and have not experienced any issues with the email not getting populated. I have confirmed that she has not made any changes to her BCeID account (They are currently associated to an email), The only change we have made on our end is to enable "Duplicate emails". I hope that did not have any negative side effects. 

Thoughts?

**Comment by lukegonis** [comment]
Shelly is still working with BCeID team to figure out the issue, still blocked

**Comment by arcshiftsolutions** [comment]
This issue is on-going:

- We're still seeing occasional IDIRs with no email associated (this is an IDIM issue)
- Personal BCeIDs do not receive the email as an attribute (known limitation at IDIM)
- We have not observed the issue with Basic or Business BCeIDs since the issues reported above

**Comment by zsamji** [comment]
closing and captured https://github.com/bcgov/sso-keycloak/discussions/73
