### ISSUE TITLE
Internal Server Error when signing in to Keycloak with IDIR

### ISSUE THREAD

**Issue by cwevans** [bcgov/ocp-sso#3]
Logging into Keycloak shows an "Internal Server Error". 

**Steps to replicate**

1. User logs into Keycloak with IDIR.
2. User updates profile (name/email/etc) and logs in.
3. User has no access
4. Admin grants access to view console
5. User logs in and receives "Internal Server Error".

NOTE: IDIR account has no email associated, Keycloak mapping may be failing.

**Comment by cvarjao** [comment]
it looks like sometimes SiteMinder sends e-mail as `null` sometimes as "empty" string. The Empty strings are the one causing duplications.

**Comment by ShellyXueHan** [comment]
IDIR idp realm has enabled duplicatie emails so IDIR accounts with no email will not be blocked from logging in. @cwevans You could configure your realm to verify email in order to prevent an "empty" string for missing email.

**Comment by cwevans** [comment]
@stephenhillier, I assume this isn't an issue anymore? Shall I close it?

**Comment by ShellyXueHan** [comment]
@cwevans yes please, thank you!
