### ISSUE TITLE
Determine the amount of increase required to support the volume spikes we're seeing

### ISSUE THREAD

**Issue by arcshiftsolutions** [bcgov/ocp-sso#306]
**Describe the issue**
Determine the amount of increase required to support the current spikes we're seeing. 

- Patroni connections?
- CPU
- Mem
- Disk
- Sticky sessions?

**Additional context**
We've noticed some instability stemming from higher volumes in the Health Gateway; we see spikes in the morning which is causing some teams to see the occasional 504. 

As part of our analysis we've noticed a couple of pods which seem to be getting sticky sessions; these pods get abused until they fall over and restart. Is there something we can do to ensure the load is distributed? Something we should discuss with the platform team. 

**Definition of done**
Ideally we determine the cause of the sticky sessions and allow the load to be more distributed. Also we may need to increase our number of pods/mem/cpu depending on our results of the sticky sessions issue.

**Comment by brycereid73** [comment]
@arcshiftsolutions @nvunnamm 
Who will look into this? thx!! -B

**Comment by arcshiftsolutions** [comment]
@brycereid73 Thinking we should include it in our (next?) sprint and assign it? At this point we should try to do further load testing and confirm the sticky issue is a thing (looking at the CPU graphs it looks like it). I would start with reaching out to the platform team to get an understanding of what we expect traffic to do when it's coming from the same IP (we know PHSA is hitting us over and over from the same service). 

![image](https://user-images.githubusercontent.com/51424896/113226342-c6763880-9244-11eb-99f6-d09b0d8c7704.png)

**Comment by arcshiftsolutions** [comment]
@nvunnamm @Sandeeparch and I just met; the guys have dug into it and here is what we've determined so far:

- We're confirming but sticky sessions do not seem to be the issue; Health traffic seems to be distributed
- Memory does not seem to be the issue
- File systems is also ok
- CPU & Network traffic seem very suspect; we see pods which are getting sudden large spike in network traffic which is causing them to crash
- We are pulling the pod logs to determine if we can get any info from the crash (CPU?)
- We're also correlating the logs to the time of crash to see if they indicate any specific source

Here is a couple more graphs of what we've seen:

(Received Bandwidth)
![image](https://user-images.githubusercontent.com/51424896/113232170-781b6680-9251-11eb-951d-4e98aa5c8f8d.png)
