### ISSUE TITLE
Make user's First and Last names mandatory

### ISSUE THREAD

**Issue by cvarjao** [bcgov/ocp-sso#31]
Prerequisites: #30 

```
Given I have a valid IDIR or BCeiD
  And An application requires me to authenticate

When I get redirected to the SiteMinder Common Logon Page
 And I authenticate myself by providing my username and password
 And The SAML response to keycloak has my first or last name missing

Then I get prompt to complete my profile by providing my First and Last name
```

**Comment by ShellyXueHan** [comment]
For teams that require first and last name for BCeID, follow the steps to setup user profile config:
- Step 1: go to your realm -> authentication -> select `First Broker Login` auth flow
- Step 2: config the execution step `Review Profile Config`, change `Update Profile on First Login` settings to on. This will make it mandatory for users to fill in the profile
