### ISSUE TITLE
Unbalanced Traffic to SSO Pods

### ISSUE THREAD

**Issue by arcshiftsolutions** [bcgov/ocp-sso#316]
**Describe the issue**
Determine why only a couple SSO pods seem to be getting all the traffic. We've noted this in a couple instances where our pods are restarting; see this issue for more detail:

https://github.com/bcgov/ocp-sso/issues/306

The pods are actually not **crashing** but are being shutdown by the liveliness probe then restarted. The liveliness probe is failing when the pod becomes unresponsive. 

**Additional context**
**CPU traffic for RH-SSO on April 6th in the AM**
![metrics1](https://user-images.githubusercontent.com/51424896/113792296-71ca3600-96fa-11eb-8b8a-05d4b2f3d32e.png)
(Note the top line is an SSO pod while the brown line is a Patroni pod...other pods are mostly idle)

**Incoming traffic at the same time**
![metrics2](https://user-images.githubusercontent.com/51424896/113792337-8c9caa80-96fa-11eb-8068-08d230f50756.png)

**Definition of done**
We need to determine why the majority of traffic is flowing to one or two pods:

- SSO configuration?
- Sticky sessions?
- ???

**Comment by brycereid73** [comment]
From Steven Barre:
We do have sticky sessions

https://docs.openshift.com/container-platform/4.5/networking/routes/route-configuration.html#nw-using-cookies-keep-route-statefulness_route-configuration

docs.openshift.com
Route configuration - Configuring Routes | Networking | OpenShift Container Platform 4.5
Also check under “Route-specific annotations” for some tunables you can set

**Comment by brycereid73** [comment]
I've asked the platform team who can make the change.

**Comment by brycereid73** [comment]
brycereid73 10:52 AM
Thanks Steven! So that’s likely the issue then. Is this something Niran has access to change? Or is it something you guys do?

Steven.Barre 10:56 AM
yup you can add annotations to your route

**Comment by brycereid73** [comment]
@arcshiftsolutions @ConradBoydElliottGustafson @nvunnamm 
Hi guys,
it looks like we have the permissions to fix this. Are you okay with suggesting Niran go ahead?

**Comment by arcshiftsolutions** [comment]
@brycereid73 Thank you for following up with the team; yes if @nvunnamm has the cycles that would be great. :)

**Comment by ConradBoydElliottGustafson** [comment]
Agreed, let’s do it but monitor the results.

**Comment by nvunnamm** [comment]
Set up the annotations and now the traffic is balanced.
The change was made 8th April 6PM. After monitoring the traffic everything looks good.
