### ISSUE TITLE
Service Level Metrics Dashboard

### ISSUE THREAD

**Issue by brycereid73** [bcgov/ocp-sso#317]
---
# User Story
* As a Service Owner
* I want a consolidated view of Operational metrics
* so that I can make decisions about service investment

## Dependencies? 
IT Security Operations
[PDF'd Email to IT Security Operations RE: SIEM/HIVE](https://app.zenhub.com/files/104518313/daf017c0-88d7-4b1a-8939-a7bc8bb94220/download)

**Comment by brycereid73** [comment]
[Email to IT Security Operations RE: SIEM/HIVE](https://app.zenhub.com/files/104518313/daf017c0-88d7-4b1a-8939-a7bc8bb94220/download)

**Comment by zsamji** [comment]
team meeting on metrics addresses strategy going forward
