### ISSUE TITLE
Keycloak Upgrade to 4.8.3 (RH-SSO 7.3.0)

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#32]
Hi,

We are upgrading Keycloak to 7.3. No major feature changes expected for existing realms, you can find the documentation here https://www.keycloak.org/archive/documentation-4.8.html 

We are planning to push the upgrade to SSO-DEV and have the community test it out. Scheduled deployment around first week of May. The testing period will take about one to two weeks.

If this plan does not work for you, please comment in this issue. Thank you!

UPDATES:
We will upgrade `dev` and `test` on the 16th May, and follow up with a `prod` deployment the following Thursday if there are no complaints.

UPDATES:
Upgrade failed, todo items
1. invalid saml session
2. update broken theme

UPDATES:
Upgrade has been finished. Still need to clean up some file used in previous rhsso7.2 (#48)

**Comment by ejarmstr** [comment]
While the use of the nonce parameter is optional when integrating with BC Services Card (BCSC), it is recommended.  If this upgrade provides Keycloak with the ability to support this then my vote would be to have this scheduled to allow us to proceed with the Registries/BCSC integration.

**Comment by pksumesh** [comment]
Here is the KeyCloak support ticket (https://issues.jboss.org/browse/KEYCLOAK-6147) to allow nonce in auth request which @ejarmstr requested above.

**Comment by ShellyXueHan** [comment]
Theme updates:
initial work done on styling, waiting for design from Design System team.

**Comment by cvarjao** [comment]
I have worked with WAM team, and we have made some changes to our integration with dev, for IDIR and BCeID, so now there should only be 1 `AudienceRestriction` element.

Before Change:
```xml
<ns2:Conditions NotBefore="2019-07-19T16:15:18Z"
                NotOnOrAfter="2019-07-19T16:17:18Z"
                >
    <ns2:AudienceRestriction>
        <ns2:Audience>https://sso-dev.pathfinder.gov.bc.ca/auth/realms/idir</ns2:Audience>
    </ns2:AudienceRestriction>
    <ns2:AudienceRestriction>
        <ns2:Audience>https://sso-dev.pathfinder.gov.bc.ca</ns2:Audience>
    </ns2:AudienceRestriction>
</ns2:Conditions>
```

After changes:
```xml
<ns2:Conditions NotBefore="2019-07-19T16:20:10Z"
                NotOnOrAfter="2019-07-19T16:22:10Z"
                >
    <ns2:AudienceRestriction>
        <ns2:Audience>https://sso-dev.pathfinder.gov.bc.ca/auth/realms/idir</ns2:Audience>
    </ns2:AudienceRestriction>
</ns2:Conditions>
```

I will try a quick test with SSO 7.3 after business hours when I have a chance.

**Comment by cvarjao** [comment]
I've done some tests by removing the route from devops-sso-dev (service: sso-dev) and adding to devops-sso-sandbox (service: sso-sbox-22). I've tried logging in as a "new" account, as well as re-login as an existing account (Same account previously created). They both worked as expected. I think we are now unblocked to attempt an upgrade again.

PS: We still need to request the same SiteMinder/SAML changes (as above) for TEST and PROD.
