### ISSUE TITLE
Investigate API Gateway (Kong) for throttling 

### ISSUE THREAD

**Issue by brycereid73** [bcgov/ocp-sso#320]
Confirm that Kong will work for our needs. And volume is acceptable. 

Can we provide QOS for important clients? Yes, but confirm with Data BC

Plan B:
3 Scale by Red Hat

**Comment by zsamji** [comment]
@ConradBoydElliottGustafson is this something we need to consider for a future sprint

**Comment by ConradBoydElliottGustafson** [comment]
Yes, we should consider it for a future sprint. Documented and moved over to Trello: https://trello.com/c/2NBbBXt5
