### ISSUE TITLE
Add `github` identity provider to ichqx89w realms

### ISSUE THREAD

**Issue by cvarjao** [bcgov/ocp-sso#325]
**Describe the issue**
Add `GitHub`  identity provider to `ichqx89w`  realms in dev, test, and prod.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Users using apps integrated with the `ichqx89w`  realm can login  using their GitHub account

**Comment by nvunnamm** [comment]
Github Idp has been added please verify.
