### ISSUE TITLE
Intermittent 504s being seen in the DEV SSO instance

### ISSUE THREAD

**Issue by arcshiftsolutions** [bcgov/ocp-sso#326]
**Describe the bug**
Navigating the UI or other calls to the service are met with a 504 response. 

**To Reproduce**
Navigate in the UI for a while or run some automation tests. 

**Expected behavior**
We should not be seeing 504s. 

**Additional context**
Has not yet been obvserved in other environments.

**Comment by arcshiftsolutions** [comment]
The team has increased our DEV instance to 5 pods; we're going to monitor further to see if there's still reports of issues.

**Comment by zsamji** [comment]
@arcshiftsolutions any suggestions on how to proceed with this ticket?

**Comment by arcshiftsolutions** [comment]
@zsamji - We haven't heard of any other issues since; suspect our changes and load (and realms) have helped.
