### ISSUE TITLE
Modify names of new BCeID realms in application realms

### ISSUE THREAD

**Issue by arcshiftsolutions** [bcgov/ocp-sso#327]
With the scripts we ran for the archaeology, we noticed the BCeID realm for Business/Basic is getting the same name as the previous Business/Basic/Personal realm. This needs to be changed to reflect the type: bceid_basic_business (Or something similar). Otherwise we'll have confusion and teams won't be able to leverage more than one realm at a time.

**Comment by zsamji** [comment]
@junminahn @ConradBoydElliottGustafson is this "incident" still athing? should i move this to the [repo ](https://app.zenhub.com/workspaces/sso-ops-support-60490daf31a4370010920b0a/board?repos=219808631&showPRs=false)where we now look at all ops things?

**Comment by junminahn** [comment]
@arcshiftsolutions I see `_bceidbasicbusiness` realms in each environment. Is that what you were initially looking for?

**Comment by ConradBoydElliottGustafson** [comment]
This issue is resolved. Marco opened this way back in the day (May 6) and it has been fixed (see Junmin's comment above).
