### ISSUE TITLE
Standard Realm onboarding for new customers

### ISSUE THREAD

**Issue by brycereid73** [bcgov/ocp-sso#328]
Create shared realm with GitHub, IDIR, and the 3 BCeID (Basic, Business, Both) (The Bus)

Create a script to onboard a customer into the Shared realm. 
- AC: Update Runbook

User documentation: What they are getting and how to use it. 

Update the service blueprint onboarding process.

**Comment by zsamji** [comment]
need to rework the landing page and all sources that lead clients to onboarding page. adding to trello ticket
