### ISSUE TITLE
Create shared realm

### ISSUE THREAD

**Issue by brycereid73** [bcgov/ocp-sso#330]
---
# User Story
* As the PO
* I want a shared realm configured in keycloak
* so that I can offer login services to new customers without needing to creating an additional realm. 

## Acceptance Criteria or Constraints
- Shared realms exists with the following names and IdP's in **Sandbox**, Dev, Test, and Prod
  - "OneStopAuth"  IDIR, GitHub (Rename OneStopAuth-B)
  - "OneStopAuth+Basic"  IDIR, GitHub, BCeID (Basic)
  - "OneStopAuth+Business"  IDIR, GitHub, BCeID (Business) 
  - "OneStopAuth+Both"  IDIR, GitHub, BCeID (Both)
- Reproducible instructions in the run book including references to scripts
- Cookie setting turned off
- Test IdP configuration via logging into the shared realm admin console with username/password for each IdP.

Tests
5 IdP's * 3 Environments = 15 tests

### Scenario 1: Example
* GIVEN IDIR Account, Example, URL https://dev.oidc.gov.bc.ca/auth/admin/OneStopAuth/console
* WHEN a user logs in with a valid IDIR
* THEN the screen refreshed to an unauthorized error.

## Dependencies? 
Team or ideally a ticket 

## Risks
Description | Impact | [Strategy](https://en.wikipedia.org/wiki/Risk_management#Potential_risk_treatments) | Contingency Plan
------------ | ------------- | ------------- | -------------
If this does or doesn't occur by... | Then this will happen, costing $? | Mitigate, Transfer, Accept, Avoid | We will do this, if it occurs
 | | |

----

# Process Guidance
### User Story
A short introductory section with the following structure:
**As a:** the person or role who will benefit from the feature;
**I want:** the feature;
**so that:** the benefit or value of the feature.

### Acceptance Tests or also called Behaviour Driven Development Acceptance criteria
A description of each specific scenario of the narrative with the following structure:
**Given:** the initial context at the beginning of the scenario, in one or more clauses;
**When:** the event that triggers the scenario;
**Then:** the expected outcome, in one or more clauses.

**Comment by brycereid73** [comment]
![19d4521f-d624-45aa-a6b7-4fd5acd89ebd.jpg](https://images.zenhubusercontent.com/60300be865f3672368ab85d1/c46ddc6a-fcbb-442d-888b-b9a5f78d5fc9)

**Comment by ConradBoydElliottGustafson** [comment]
@brycereid73 Is this done?

**Comment by nvunnamm** [comment]
yes Conrad we have all the mentioned realms and tested those.
