### ISSUE TITLE
Client creation Terraform Project

### ISSUE THREAD

**Issue by brycereid73** [bcgov/ocp-sso#331]
As the PO, I want a Terraform repository to manage Clients in the Standard Realms so that the standard config is consistently applied.

Acceptance Criteria
- Client configuration includes a mapper to capture the name of the identity provider so that applications can check to see how the user logged in.
- Confirm that the Terraform definition includes an option to include a Unique Name for the client
- Valid redirect URLs are required and should be added to the Terraform definition at runtime. 
- Client secrets are not checked into the repository
- Client definitions are managed in such a way as we know what realm they are going to. The standard realms are:
-- DEV - "onestopauth"
-- DEV - "onestopauth-business"
-- DEV - "onestopauth-basic"
-- DEV - "onestopauth-both"
-- TEST - "onestopauth"
-- TEST - "onestopauth-business"
-- TEST - "onestopauth-basic"
-- TEST - "onestopauth-both"
-- PROD - "onestopauth"
-- PROD - "onestopauth-business"
-- PROD - "onestopauth-basic"
-- PROD - "onestopauth-both"

![20189812-b53d-4fb5-ad7b-db0b6c29fe3a.jpg](https://images.zenhubusercontent.com/60300be865f3672368ab85d1/bffb25f1-1aec-4831-90ec-4af809007abe)

**Comment by junminahn** [comment]
this is the first task I will work on.
