### ISSUE TITLE
Client info capture

### ISSUE THREAD

**Issue by brycereid73** [bcgov/ocp-sso#332]
- Redirect URLs
  - Client Name
  - PO Info: IDIR, Email, Phone, Name

  - Information for BCeID approval (see images from realm-o-matic)

![Screenshot 2021-05-10 153618.png](https://images.zenhubusercontent.com/5ff4dccf88cdaf15164ebd58/38dfe1b8-c124-421e-85e3-7249135d8337)![Screenshot 2021-05-10 153701.png](https://images.zenhubusercontent.com/5ff4dccf88cdaf15164ebd58/ec0c81c1-41cd-43fa-b151-b34a093aadb5)Update/implement process for tracking Client details

**Comment by ConradBoydElliottGustafson** [comment]
I just made this part of the DevOps request form for now.
