### ISSUE TITLE
Fix Sandbox Environment

### ISSUE THREAD

**Issue by brycereid73** [bcgov/ocp-sso#334]
Criteria:
All testing can be done in Sandbox before Dev/Test/Prod. 

IdP's need to be setup. Including requests sent to WAM team.

**Comment by zsamji** [comment]
@ConradBoydElliottGustafson believe we can close this epic unless im missing something

**Comment by ConradBoydElliottGustafson** [comment]
Yes, our Sandbox namespace has DEV test prod again. We are good!
