### ISSUE TITLE
Create CI/CD pipeline for client management with terraform

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/ocp-sso#343]
Now that we have a structure for a repository to store standard realm client configurations, it is possible to run Terraform against the KeyCloak instances and perform changes.

The ideal situation would be to have these changes propagated automatically when the changes are checked into master.

It would be lovely to use Terraform cloud to do this. we have an AWS landing zone account.

**Comment by zsamji** [comment]
done
