### ISSUE TITLE
Customer Client Request Automation

### ISSUE THREAD

**Issue by brycereid73** [bcgov/ocp-sso#347]
# User Story
As an SSO Admin, I'd like a way for a customer to submit a request for a new or updated client that is automated so that it's easier and less error prone for the customer. 

## Acceptance Criteria or Constraints
* I'll see this or
* The solution will conform to this or
* Non-functional requirements

### Scenario 1: xxxxxx
* GIVEN ... 
* WHEN ... 
* THEN ...

**Comment by brycereid73** [comment]
@junminahn Please comment on this ticket. Share what you were thinking so Conrad can review.

**Comment by brycereid73** [comment]
@ConradBoydElliottGustafson Hey Conrad, Junmin suggested this during our stand up today (May 31). So, I created this placeholder story for him to add more details.

**Comment by junminahn** [comment]
@brycereid73 thank you for creating this ticket.
@ConradBoydElliottGustafson What I suggested is to provide an `issue template` for users who want to create new clients.
As the `issue get created` GitHub action can listens that events and do following steps on behalf of the requester automatically:
1. Make a new branch including the new client files.
2. Make a PR to the main branch to get reviewed.

The main benefit would be that the requesters do not need to understand the local environment/ process to create client files and PRs.

**Comment by ConradBoydElliottGustafson** [comment]
That's a great idea. There already is an issue template here: https://github.com/BCDevOps/devops-requests/blob/master/.github/ISSUE_TEMPLATE/keycloak_standard_client_request.md

**Comment by zsamji** [comment]
think this is covered in internal mvp 1. @ConradBoydElliottGustafson please correct me if i'm wrong

**Comment by ConradBoydElliottGustafson** [comment]
Our new web app makes this story redundant.
