### ISSUE TITLE
Migration Strategy

### ISSUE THREAD

**Issue by brycereid73** [bcgov/ocp-sso#353]
1. Prioritized List - Done
2, Identify unused Realms
3. Create Comms - Lada
4. These are the steps
      - Create Process - Dev Team

**Comment by zsamji** [comment]
waiting to hear from team on updates to this @ConradBoydElliottGustafson

**Comment by ConradBoydElliottGustafson** [comment]
@zsamji Bryce and Stephanie had the ball on this one. Can we ask Stephanie for a knowledge transfer?

**Comment by zsamji** [comment]
moved to my internal trello board
