### ISSUE TITLE
Define approach and test

### ISSUE THREAD

**Issue by brycereid73** [bcgov/ocp-sso#354]

**Comment by zsamji** [comment]
not sure what this is related to @ConradBoydElliottGustafson thoughts?

**Comment by ConradBoydElliottGustafson** [comment]
I don't think there is risk in deleting this. Looks old and not groomed.

**Comment by ConradBoydElliottGustafson** [comment]
Ah, I see the context here. It is inside an epic "Migrate Clients to Standard Realm"
