### ISSUE TITLE
Add "How to" for alerts in runbook. 

### ISSUE THREAD

**Issue by brycereid73** [bcgov/ocp-sso#355]
We have a runbook wiki in BCGov Teams. Niran documented how to add alerts in sysdig.

**Comment by ConradBoydElliottGustafson** [comment]
@brycereid73 Please clarify this so that the team can action it.

**Comment by ConradBoydElliottGustafson** [comment]
@brycereid73 Nevermind.

**Comment by nvunnamm** [comment]
Document has bee setup in https://teams.microsoft.com/_?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc#/tab::96dcc221-29f2-4cab-9474-a68ef02c19de/19:2f9f5a8a2a524004bdd268447c94c0b6@thread.tacv2?threadId=19:2f9f5a8a2a524004bdd268447c94c0b6@thread.tacv2&ctx=channel&isTeamLevelApp=false
