### ISSUE TITLE
Implement storage monitoring and notification is in place for SSO

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/ocp-sso#36]
Determine what monitoring is in place already and determine what additional measures, if any are needed to ensure that storage can be proactively allocated.

**Comment by ShellyXueHan** [comment]
### Tasks:
- [ ] create sysdig alert on filesystem usage
- [ ] create RC channel notification

**Comment by patricksimonian** [comment]
sysdig file system alert on patroni pods created to alert #sso-ops channel!
