### ISSUE TITLE
Update Public-Facing docs to reflect Spring 2021

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/ocp-sso#367]
New (Aug. 4): Add guidance on IDP selection
Update to document the new tool when it gets released.

Updating Web Guidance for Keycloak (Conrad):

1- Realm Request on GitHub – delete this page and make a new issue template
DONE

2 - Digital.gov - Conrad wants to fix the last paragraph under the first heading
https://digital-gov-frontend-prod-c0cce6-prod.apps.silver.devops.gov.bc.ca/common-components/keycloak-sso

3 - Wiki – fix it and remove Realm-o-matic https://github.com/bcgov/ocp-sso/wiki
Wiki main page should have short description (same content as all the other places)
Rest of it is technically useful 
	Should clearly state that it’s app responsibility to ensure people aren’t using wrong IDP to log into service
DONE

4 - DevHub Realm Creation – ask Devhub to delete this page - outdated
https://developer.gov.bc.ca/Authentication-and-Authorization/Request-SSO-Realm-Creation
DONE

5 - DevHub Service Definition – conform this to Digital.gov
https://developer.gov.bc.ca/Authentication-and-Authorization/BC-Government-SSO-Service-Definition
DONE

6 – Client request on GitHub (new) DONE

7 – Update client request on GitHub – new name for service and give the choice of public or confidential -- DONE

8 -- add mapping stuff to the wiki

9 – Update Wiki with name of service and choice of options DONE

10 -- Rewrite digital.gov

11 – add a description of how to use kc-idp DONE

12 – Fix the DevHub pages (name of service, etc.) DONE

13 -- update when new service is launched

**Comment by zsamji** [comment]
@ConradBoydElliottGustafson  can you add me to this zenhub board?

**Comment by zsamji** [comment]
Completed for recent internal demo
