### ISSUE TITLE
Ops Event Log Tools

### ISSUE THREAD

**Issue by brycereid73** [bcgov/ocp-sso#368]
### User Story or Stories
As a | I want | so that
------------ | -------------  | -------------
DevOps Engineer | to review the **openshift platform** logs associated with keycloak |I can investigate issues
DevOps Engineer | to review the **keycloak server** logs associated with keycloak |I can investigate issues
DevOps Engineer | to review the **keycloak db logs** logs associated with keycloak |I can investigate issues

### Acceptance Criteria
Real-time for troubleshooting
Historical for trend analysis

**Comment by zsamji** [comment]
Done
