### ISSUE TITLE
Ensure database backups are in place and functioning for SSO

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/ocp-sso#37]

**Comment by caggles** [comment]
@sheaphillips @ShellyXueHan, does this ticket require something more than the confirmation messages that come into the sso-ops rocketchat channel, or is this ticket out of date?

**Comment by ShellyXueHan** [comment]
We've added the backup container for keycloak, and tested. So this ticket is go to close now. Thanks for reminding!
