### ISSUE TITLE
SPIKE: Examine Cognito Adaptors

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/ocp-sso#374]
Goal: for customers to be able to quickly and easily integrate their project with an app client on Cognito managed by the SSO team.

Come up with some common criteria for adaptors to fulfill (or not)
Look at the "official" adaptors provide by AWS (amplify project?)
See if there are any good open source ones
Document the adaptors that exist (without evaluating them all)
Specifically look at if any of them support stateless API using bearer-token JWT (instead of cookies)
Also interested in how much network traffic they produce (i.e. not calling the OIDC provider on every request)

AC: short little report on the adaptor libraries that exist and what scenarios they support

Criteria:

- open source?
- what credentials does it require?
- does it support a confidential client (or only public)
- does it support "IDP Hint"?
- can we use it to make a stateless API
- cookies or HTTP headers?
- maintainability -- how official is it or how much support does it have (community or other)

**Comment by ConradBoydElliottGustafson** [comment]
One thing that might be a criterion is whether or not the adaptor can be used with a client-secret or if it needs to be used with a public app client.

**Comment by junminahn** [comment]
The evaluation work is documented in
https://github.com/bcgov/cognito_example_client_app/blob/main/docs/adapter-evaluation.md
