### ISSUE TITLE
Configure direct Cognito integration to BCeID

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/ocp-sso#378]
We tested out BCeID configuration from Cognito, but it would be better to have a real configuration to SiteMinder. Stephanie sent out an email on June 11 to the WAM team to ask them about this, as they need to set up the integration and give us the details to use to set up the IDP in Cognito.

This will probably also require approval from Tim McGuire.

**Comment by ConradBoydElliottGustafson** [comment]
This needs an iStore request with all the trimmings. Jesse sent Stephanie the forms, but I believe it's the same thing we recently did for BCeID Basic, BCeID Business and BCeID Basic+Business. Are you able to kick it off for us @brycereid73 pretty please?

**Comment by zsamji** [comment]
zorin's got this
