### ISSUE TITLE
Set up a Cognito SAML connection

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/ocp-sso#384]
Just a test one to any SAML IDP to prove we can do it.

**Comment by jlangy** [comment]
Made a sample connection [here](https://1234321.auth.ca-central-1.amazoncognito.com/login?client_id=79l1u8npjm0j5ll65fch2602tv&response_type=code&scope=aws.cognito.signin.user.admin+email+openid+profile&redirect_uri=https://example.com),

which is an app client with SAML connection to okta. Step-by-step walkthrough to setup [here](https://www.techpearl.com/blog/integrating-okta-with-amazon-cognito/index.html)

When connecting, two things to note about using the returned code to post to cognito:
- When posting to cognito to get a token, parameters need to be in the body as x-www-url-formencoded
- If the app client has a secret, add to params as `client_secret`
