### ISSUE TITLE
Configure direct Cognito integration to GitHub

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/ocp-sso#386]
We know we can't do direct OIDC to GitHub (only OAuth 2.0)

Our current strategy is to wait for GitHub Enterprise to be purchased. This level of account provides access to GitHub SAML endpoints (we think). So this ticket is blocked until then.

If we don't get SAML, it may be possible to create an OIDC wrapper using AWS services like Lambda functions. There is at least one open source project that does this (and it has Cloud Formation Templates).

**Comment by zsamji** [comment]
will revisiting once we've got a stance on our POCS
