### ISSUE TITLE
Standard Realm Workflow Tool

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/ocp-sso#389]
### MVP AC
- Real T&C's
- IDIR/Github only
- Landing Page (Minimum content)
      * Needs design complete
      * Needs implementation
- Support page
    - Links to online content only
- Admin Notifications (Github)
- Customer Notifications - Decision point: no customer notifications in MVP -- just a dialog when they submit telling them to come back.
* Update public-facing documention
- Give customer a choice on confidential or public client

### ISSUE (Resolved)
Do customers need to be notified that their request is complete/approved?
OPTIONS:
- Build email notification capability
- Manually send email copying email address from **somewhere?**
This one -> In context information explaining they need to check back periodically

### Next Release
- Notification Slide-Out
- Support page
    - Form

**Comment by zsamji** [comment]
addressed in MVP released in September 2021
