### ISSUE TITLE
Logout not working for IDIR/BCeID users

### ISSUE THREAD

**Issue by cvarjao** [bcgov/ocp-sso#4]
The SiteMinder [logout page](https://logontest.gov.bc.ca/clp-cgi/logoff.cgi) is not redirecting back to KC to finish the logout process.

This can manifest with a `invalidFederatedIdentityActionMessage` (Login Error)

Workaround:
- Start a new/fresh browser when switching users or IdP (IDIR <-> BCeID)

**Comment by ytqsl** [comment]
We have a workaround via the web client:
1. the client requests logout from the server, it returns OIDC logout redirect response, and asks for the return url to be another logout endpoint. After OIDC signout is completed, the returned endpoints returns redirect to siteminder logout url.

.net example can be found here - https://github.com/bcgov/embc-ess/blob/r1develop/embc-app/Controllers/LogoutController.cs

**Comment by arcshiftsolutions** [comment]
We use a similar style to @ytqsl ; in our case we chain the call from SM logout -> redirect -> KC logout -> redirect -> KC login.

**Comment by zsamji** [comment]
to be addressed in sprint ending Sept 2
