### ISSUE TITLE
Configure Sandbox KeyCloak Instances

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/ocp-sso#401]
In order to be able to develop the workflow tool, we need a QA environment for Keycloak that matches closely to production.

AC:
1.  NIRAN: DEV, TEST, PROD keycloak instances running in Sandbox namespace DONE
2.  Niran: User accounts for Conrad, Junmin and Jon on all KC instances DONE
3. Niran:  Create the 4 standard realms. We don't care about IDPs in the realms at this time for this purpose. ???
4. Junmin: Admin_API working on all instances the same way we did it in the production instances. Create a terraform_api client in master. and use it as a service account. Limit the privileges to full control over the 4 standard realms.

**Comment by ConradBoydElliottGustafson** [comment]
@nvunnamm has #3 been completed?

**Comment by nvunnamm** [comment]
Yes, Comrad that's complete.
