### ISSUE TITLE
Tech Debt: Clean up repo structure so we don't have to have a copy

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/ocp-sso#411]
Currently we have sso-terraform and sso-terraform-dev. They are copies of each other which makes it a bit tricky to make improvements.
Extract core functionality to avoid duplicate code.

Design ideas:
1. Modularize the terraform code and extract to another repo
2. Github CI/CD actions can also be extracted into another repo
3. Github workflow request actions (that get called from the workflow tool) can be extracted into another repo
3. Client configurations for the QA environment can live on a separate branch (or separate repo) that never gets merged to main branch

**Comment by zsamji** [comment]
@ConradBoydElliottGustafson help me understand if we've discussed this yet

**Comment by zsamji** [comment]
@ConradBoydElliottGustafson @junminahn does our delete function for this sprint handle this request? If not, please PO language this for me :)

**Comment by junminahn** [comment]
@zsamji This issue is not related to the 'delete' functionality. but related to one of the tasks we've already worked on:
https://trello.com/c/8wGt9TSg/78-modularize-github-actions (which covers #2 and #3).

We can create a separate tech debt ticket for #1 and I believe #4 is no longer applicable.

**Comment by zsamji** [comment]
created in trello structure. closing
