### ISSUE TITLE
Get a service account for GitHub

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/ocp-sso#416]
We need a "team" IDIR that we can use to create a GitHub service account so that the GitHub token used for security to call the Github actions is not connected to a personal account.

**Comment by ConradBoydElliottGustafson** [comment]
Var is returning on Monday July 19. Until then it's hard to get email stuff.

**Comment by ConradBoydElliottGustafson** [comment]
Var has asked that we get our new PO to do this when he or she starts on the team.

**Comment by zsamji** [comment]
done
