### ISSUE TITLE
Fix github authorization flow

### ISSUE THREAD

**Issue by jlangy** [bcgov/ocp-sso#417]
The github secret is not passing correctly in the dev environment. Note the secret passes from github secrets => actions => tfvars => lambda, somewhere in this flow something is breaking (works in sandbox when setting directly in cli var)

**Comment by zsamji** [comment]
@jlangy @ConradBoydElliottGustafson is this a thing we should focus on for an upcoming sprint?

**Comment by ConradBoydElliottGustafson** [comment]
I believe this is fixed.

**Comment by jlangy** [comment]
yes this is fixed
