### ISSUE TITLE
Implement Support page final designs

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/ocp-sso#450]
BCGov.SSO@gov.bc.ca

**Comment by zsamji** [comment]
not sure what this is. assuming its wiki related documentation. @ConradBoydElliottGustafson

**Comment by ConradBoydElliottGustafson** [comment]
![image](https://user-images.githubusercontent.com/75282706/129974327-a7b64683-b897-4f7c-a6ca-32fd9341c9e5.png)
@zsamji If you look at the card in ZenHub, you can see that it is part of the epic "Standard Realm Workflow Tool". So if that is the only context on this "subtask" is that it was related to our web application. I think Emir has designs for a "support" page that is the next evolution from what we have now which is just pointing out to the wiki.
