### ISSUE TITLE
Split event tracking into separate entity

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/ocp-sso#453]
Previously we had events like "submitted" as a boolean + timestamp on the main entity.

Because we now let customers edit their redirect URLs, there can be "n" events and we need a many-to-one relationship

AC:
New table for "event".
Fields: PK, request key, event code, timestamp

So when the update is requested that is an event
Wen the update is fulfilled GitHub actions will call the API and the new event will be recorded
We will keep a "state" property in the main entity.

**Comment by jlangy** [comment]
add a null userid for now
request-{event}-{success | fail}
