### ISSUE TITLE
Remove GitHub from Prod Standard Realms

### ISSUE THREAD

**Issue by brycereid73** [bcgov/ocp-sso#464]
**Describe the issue**
GitHub is an unapproved IdP and requires an exemption to be used by BC Gov web applications. Currently, the Pathfinder SSO team's Standard Realm's include GitHub by default. 

**Additional context**
GitHub will continue to be included as a default IdP in the Dev and Test Standard Realms.

**Definition of done**
Remove the GitHub IdP configuration from the 4 standard realms in the Keycloak oidc.gov.bc.ca production environment

**Comment by juhewitt** [comment]
let me know where I need to be to support the appropriate use case and exemption for SSO and GitHub IDP.  I have multiple legitimate use cases to continue usage.  @gjlawran

**Comment by juhewitt** [comment]
Lets also update this information to accommodate when to use, and not use etc.  https://developer.gov.bc.ca/Authentication-and-Authorization/BC-Government-SSO-Service-Definition

**Comment by gjlawran** [comment]
Definitely would be good to give some guidance on use and risks associated with different IDPs - to ensure the right solution is being used.  Kind of ironic that we are having this discussion  on GH.   Do they accept a different IDP?

**Comment by brycereid73** [comment]
@ConradBoydElliottGustafson FYI

**Comment by brycereid73** [comment]
@nvunnamm 
Remove from the 4 standard realms in oidc.gov.bc.ca not dev or test.

**Comment by brycereid73** [comment]
@juhewitt Hey Justin, Github is being removed from the four standard realms only. Owners of realms can use Github as long as they are following all the appropriate policies, etc.  

Let me know if you still have a concern.

Thanks,
Bryce

**Comment by gjlawran** [comment]
@brycereid73   - We have concern over removal from the standard realms.   Do you have communication plan and timeline for this change?

**Comment by zsamji** [comment]
@gjlawran we've had a chat with @juhewitt on this. If we need to still discuss, please reach out to me and we can have a meeting to discuss outstanding concerns.
