### ISSUE TITLE
Setup integration between Azure AD & SSO for IDIR

### ISSUE THREAD

**Issue by arcshiftsolutions** [bcgov/ocp-sso#471]
**Is your feature request related to a problem? Please describe.**
Setup integration between Azure AD & SSO for IDIR. IDIM has setup a test instance which we can use to ensure we get the attributes we need in the token payload.

**Comment by arcshiftsolutions** [comment]
We have completed this integration. Chris was able to provide the IDIR GUID & user ID; after we added mappers to the identity provider, the attributes are now available.

**Comment by zsamji** [comment]
recreating in [this repo](https://github.com/BCDevOps/devops-requests/issues/new?assignees=jlangy%2C+junminahn%2C+arcshiftsolutions%2C+zsamji%2C+nvunnamm%2C+ConradBoydElliottGustafson&labels=keycloak-realm%2C+pending%2C+sso%2C+standard+realm%2C+configuration&template=keycloak_configuration_change.md&title=) so it gets pulled into our daily standup view.
