### ISSUE TITLE
Cannot Delete Client Scope if it is in Default Client Scopes

### ISSUE THREAD

**Issue by james-hollinger** [bcgov/ocp-sso#54]
Client Scopes that are added to Default Client Scopes cannot be deleted, resulting in this unhelpful error message: 

"javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement"

**Comment by ShellyXueHan** [comment]
@james-hollinger I cannot reproduce this issue anymore now. Can you confirm this is resolved or still exist? Thanks!

**Comment by james-hollinger** [comment]
Looks like in the new version, there is a much more helpful error message stating that the Client Scope is in use and cannot be deleted.
