### ISSUE TITLE
Stabilize Keycloak (New Arch)

### ISSUE THREAD

**Issue by arcshiftsolutions** [bcgov/ocp-sso#61]
As owner of a client app, I want to restrict or enable users to use specific policies regarding the login type.
## Description
* Eventually, we want to turn off the existing personal BCeID option
* BCeID integration will be restricted to 3 realms. Basic, Business or Both
* Personal BCeID’s will continued to be used
* New requests for integration with personal are restricted with possible exception
* ISSUE: Personal BCeID field … email is empty so SAML is invalid
* Eventually, we want to turn off the existing personal BCeID
## Acceptance Criteria
* Scenario 1
  * GIVEN: Basic Realm
  * WHEN: 
  * THEN:
* Scenario 2
  * GIVEN: Business Realm
  * WHEN: 
  * THEN:
* **Scenario 3 Priority**
 * GIVEN: I'm creating an application that needs basic and business BCeID logins
 * WHEN: I go through the realm-o-matic process 
 * THEN: I end up with a client that can facilitate logins to basic and business but NOT personal
* Scenario 4
  * GIVEN: Personal BCeID
  * WHEN: Requests for integration with the everything Realm
  * THEN: Inform user they need special approval from WAM team
## Change Management Plan
* New requests will be directed to use new options only
* Legacy account migrations TBD
## Activities
* Document this process within a service blueprint format
  * Note: Process is for BCeID approval first (This process exists today)
* Get a list of Realms that are consuming personal BCeID by querying the end points with user names to establish types (Conrad offered to help pair program) Note: this is needed for migration. 
* Validate with users which type of realm they require. If a realm has only basic, it’s possible they’ve never had a business logging in. Double check they don’t need “both” even though it looks like they only need “basic”.
* Build new segregated realms systems. Test in Sandbox **PRIORITY**
  * WAM team has set up test environments and we need to set up the realms
  * Christine Sutherland is the lead on the WAM team. 
  * iStore ticket from Shelly says that the WAM team is ready.
* SAML Config afterwards. However, the playbook is only for IDIR. Need to update Ansible Playbook
* Migrate accounts into new realms
## Additional Notes
* Conrad and Marco are suggesting that the users could participate in the migration. 
* When we provision using realm-o-matic we should add logic to choose 1, 2, or 3
* Maybe a script that users can opt to use and migrate their realm to the new structure via Real o matic interface (Script is needed)
#Timeline
* Var suggested alignment with vanilla realm. 
Tech tasks

## OLD Ticket Description
Create separate realms for BCeID Personal/Basic/Business.

This will allow fine grain access to each of the BCeID account types. (i.e. if an application only supports Basic, only Basic should be available; currently all three types are always available)

What's required?
- Three new BCeID realms (one for each type)
- New BCeID credentials for each realm (iStore orders)
- Migration scripts to allow teams to move to the new model seamlessly 
- Some work will need to be done to determine what each application supports (Nick Mailhot to support)

**Comment by ShellyXueHan** [comment]
Update:
- currently waiting for SiteMinder federation services to be ready

**Comment by zsamji** [comment]
have standard realms
