### ISSUE TITLE
Reference Link in Readme is 404

### ISSUE THREAD

**Issue by jeremy-vernon-bcgov** [bcgov/ocp-sso#62]
At the foot of the Readme is the following:

https://access.redhat.com/documentation/en-us/red_hat_jboss_middleware_for_openshift/3/html-single/red_hat_jboss_sso_for_openshift/#Example-Deploying-SSO

Which is 404 on RedHat's website.

**Comment by ShellyXueHan** [comment]
Link updated. Thx!
