### ISSUE TITLE
Keycloak doesn't re-evaluate DNS for the database

### ISSUE THREAD

**Issue by cvarjao** [bcgov/ocp-sso#63]
When patroni failover to a new master, keycloak doesn't seem to detect that and keeps re-using the IP of the previous master which is now in read-only mode. It seems to keep a lock to the IP.

It may be related to [java DNS lookup caching](https://docs.oracle.com/javase/6/docs/technotes/guides/net/properties.html#nct)

**Workaround**: [Flush connections](https://github.com/bcgov/ocp-sso/wiki/2.1-Troubleshooting#flush-connection-pool-for-all-pods-of-a-deployment-config) to fore connections to be established.

**Comment by brycereid73** [comment]
Test if this is still an issue in Sandbox.

**Comment by arcshiftsolutions** [comment]
This is still an issue; our team had issues during a node drain recently.

**Comment by zsamji** [comment]
closing and tracking here https://github.com/bcgov/sso-keycloak/discussions/72
