### ISSUE TITLE
Account already exists message in my BCPARKS production realm

### ISSUE THREAD

**Issue by dbayne** [bcgov/ocp-sso#66]
How do I fix this, only happens in Prod realm when I log in using my IDIR. Message comes up with 
Account already exists with the option of review profile or add to existing account. I am trying to get to the admin console which is fine when I log in to Test and Delivery Realm instances.

**Comment by ShellyXueHan** [comment]
what's the IDIR account that you are using to login?  Is there any recent IDIR account update, like email change? In terms of the newly requested realm, there's a mismatch on the IDIR account. I've updated it and they should be all set for you now.

**Comment by dbayne** [comment]
idir\dbayne and no recent updates on this.

**Comment by ShellyXueHan** [comment]
I don't see any duplicate accounts created with it. I've logged you out from all sessions now, could you try login to the prod realm again?

**Comment by dbayne** [comment]
I still get Account already exists, user with email david.bayne@gov.bc.ca already exists.

**Comment by ShellyXueHan** [comment]
is it possible that you have a github account with the same email address? Your realm has the login setting to enforce unique email address, which is taking you to that page. I've deleted your account in the realm, try again now. You should see a forbidden error atm.

**Comment by dbayne** [comment]
Forbidden message now, and yes, I did have the same email for my GitHub account but I changed it, because I thought that was the problem.

**Comment by ShellyXueHan** [comment]
regranted the admin access to your IDIR account, try again. also checked the github accounts on KC, doesn't look like the email has been updated yet. You might need to login again with Github account to have that synced.

**Comment by dbayne** [comment]
I have changed my primary email on GitHub account and logged in to Prod realm and looks all good now, thanks!
