### ISSUE TITLE
Reset IDIR account in keycloak

### ISSUE THREAD

**Issue by nitin-freshworks** [bcgov/ocp-sso#67]
Hi, 
I had problems with IDIR after coming back from  vacation, so the IDIR team has reset/change my password, but facing issues with Keycloak login. Since guid in keycloak changed. Please reset my account in keyclaoak

IDIR - NARORA

**Comment by ShellyXueHan** [comment]
captured in https://github.com/bcgov/ocp-sso/issues/68 closing this ticket.
