### ISSUE TITLE
KeyCloak login issue: user already exists

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#68]
## Background:
After login with the identity provider, user sees a KeyCloak page with a message `User with <email/username> already exists. How do you want to continue?` from the application realm

## Reference:
<img width="622" alt="Screen Shot 2020-03-19 at 2 20 33 PM" src="https://user-images.githubusercontent.com/36056216/77116521-8eaba280-69ed-11ea-9106-5d2c0b75a5f3.png">

## Steps to debug duplicated email:
- fist of all, try to clear cache and reopen browser to test a clean start
- check with realm admin on the login settings: `Realm Settings` -> `Login` tab -> `Login with email` If this field is set to true, no new accounts with duplicate email address can be created.
- check if any user account in the realm has the same email address as your currently account. This usually happens between two accounts from the same person (e.g.: IDIR and BCeID with the same email), or different accounts with ***empty email attributes***.
- If that's the case, either enable `Duplicate email` setting, or update one of the accounts with another email address

## Steps to debug duplicated username:
- fist of all, try to clear cache and reopen browser to test a clean start
- have you recently updated your IDIR/BCeID account? If so, please request for a KeyCloak user update at: https://github.com/BCDevOps/devops-requests
- if above does not apply, please contact RocketChat channel sso

**Comment by garywong-bc** [comment]
NOTE I now see a `Configure -> Realm Settings -> Cache`  option that MDS could've tried prior to deleting the 2nd account (with the same email).  The 1st account did NOT show up in the list of users but may have been in the cache.  In the future, if this happens again we should try clearing the cache before making any config changes.

**Comment by aaabramov** [comment]
> NOTE I now see a `Configure -> Realm Settings -> Cache` option that MDS could've tried prior to deleting the 2nd account (with the same email). The 1st account did NOT show up in the list of users but may have been in the cache. In the future, if this happens again we should try clearing the cache before making any config changes.

You saved me hours of investigation.. I was getting 409 for deleted user )

**Comment by zsamji** [comment]
closing as it is captured https://github.com/bcgov/sso-keycloak/discussions/70
