### ISSUE TITLE
Disable KeyCloak impersonation

### ISSUE THREAD

**Issue by k-zang** [bcgov/ocp-sso#70]
Please remove the impersonation role for all users.

Reasoning:
Impersonation as a concept is only appropriate for enterprise administrators to help with diagnosing issues for employees within their own enterprise. Even then, it would only be acceptable to be used sparingly and with significant oversight/audit (for example, this permission would have to be requested and approved by the CISO on a case-by-case basis).
 
With Keycloak, impersonation could likely be used to allow administrators to see a different citizen’s Health Information. There are no circumstances where this would be appropriate.

**Comment by BcGovNeal** [comment]
Realm admins can do this themselves.  Just remove the `impersonation` role from the `realm-management` role mappings.

Once removed, only the server admins can add impersonation back.

**Comment by k-zang** [comment]
Who does "realm admins" consist of? The other ministry's clients who are building containers utilizing KeyCloak?

**Comment by BcGovNeal** [comment]
That would be each ministry's own development team, or the person who requested the realm to be created.

**Comment by k-zang** [comment]
Is there a way to set this as default (and force it on existing) so as not leave it up to the realm admins since we have no way of enforcing it? The reason I ask is that I was told to submit the request here to get it done.

**Comment by BcGovNeal** [comment]
Why aren't you able to enforce it?  Realms are owned by ministry teams and they can make this change themselves.

Once the role is removed, the realm admins can't add it back again themselves.  Only the platform admin team can add it back.

**Comment by k-zang** [comment]
I don't know why. I have no access to any of it as I don't work in dev. I'm simply security. All I know is I was asked to make the request by my management, and the devOps people told me to do that by submitting the ticket here. Can you do it?

**Comment by BcGovNeal** [comment]
I'm not part of the platform admin team, so I can only manage my own realms.

You need to find out who owns the realm on your devops team and have that person do what I said in my first reply.

**Comment by k-zang** [comment]
Ok, Thanks. I'll take this all back to Shelly.

**Comment by ShellyXueHan** [comment]
issue resolved: https://github.com/bcgov/ocp-sso/issues/74
