### ISSUE TITLE
KeyCloak Upgrade (7.3 -> 7.4)

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#72]
Test and upgrade to RH SSO v7.4: https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.4/html-single/release_notes/index

**Comment by ShellyXueHan** [comment]
Security advisory out for keycloak/RH SSO:
https://access.redhat.com/errata/RHSA-2020:2814
https://access.redhat.com/errata/RHSA-2020:2816

**Comment by zsamji** [comment]
@ShellyXueHan once your internal testing is done, a friendly reminder to include IDIM as it relates to configs for new clients
