### ISSUE TITLE
Pathfinder SSO requesting authorization for unwanted private information from GitHub profile

### ISSUE THREAD

**Issue by praveen-aot** [bcgov/ocp-sso#75]
Pathfinder SSO requesting authorization for unwanted private information from GitHub profile such as Organization, Organization Members and Private Project Boards.

**Comment by ShellyXueHan** [comment]
@praveen-aot please provide more context on this and the concerns. Here's a bit of the background: we are collecting GitHub user's info from BCGov GitHub organizations (bcgov, BCDevOps, etc). When user first login via GitHub, they are provided the page where they could design if they want to give the information.

**Comment by ShellyXueHan** [comment]
Please reopen the ticket with updates.
