### ISSUE TITLE
wandering links for 'registration,' 'login,' and 'forgot password' buttons in BCGov Keycloak theme 

### ISSUE THREAD

**Issue by Maralsotoudehnia** [bcgov/ocp-sso#77]
@ShellyXueHan per our discussion, there are three similar bugs that impede registration and login:

1. A user cannot click the 'forgot password link.' It wanders. See image below for link reference.
	
![image](https://user-images.githubusercontent.com/45858774/86952294-a1b2c180-c107-11ea-8c89-21678b0a8fe7.png)

2. 'registration button' doesn't work without funky hold+clicking (same thing: it wanders!). See image below for link reference.
![image](https://user-images.githubusercontent.com/45858774/86952542-03732b80-c108-11ea-95c8-2581a81cca40.png)

3. login link on registration page doesn't work without funky hold+clicking (more wandering). See image below for link reference.
![image](https://user-images.githubusercontent.com/45858774/86952693-39181480-c108-11ea-8bc1-d66c7c57a6df.png)

Let me know if you have further questions. Best,
M

cc @matthieu-foucault @kriscooke

**Comment by matthieu-foucault** [comment]
As I mentioned in RC, what I could debug from my browser is that in `styles.css:L62` the CSS selector is `a.zocial, #kc-login, a.zocial.keycloak-oidc, a:active`. I think that removing `a:active` from the selector will solve the issue.

**Comment by ShellyXueHan** [comment]
this fix will be part of the upgrade: https://github.com/bcgov/ocp-sso/issues/72

**Comment by ShellyXueHan** [comment]
@matthieu-foucault @Maralsotoudehnia please double check if issue has been resolved now.

**Comment by Maralsotoudehnia** [comment]
@ShellyXueHan I'll test it out today/tomorrow and update accordingly. Thank you!!!

**Comment by matthieu-foucault** [comment]
@ShellyXueHan @Maralsotoudehnia I tested in the dev instance and can confirm that the theme is fixed. Thanks again!
