### ISSUE TITLE
SSO User Registration Cache Issue

### ISSUE THREAD

**Issue by Maralsotoudehnia** [bcgov/ocp-sso#79]
Hi @ShellyXueHan:

@matthieu-foucault eloquently described the issue we're encountering as follows: 

The issue was reproduced (sometimes) by 
1) clicking on our registration button, which is a link to https://sso.pathfinder.gov.bc.ca/auth/realms/pisrwwhx/protocol/openid-connect/registrations?client_id=cas-ciip-portal&response_type=code&scope=openid&redirect_uri=https%3A%2F%2Ftest.ciip.gov.bc.ca%2Flogin%3Fauth_callback%3D1
2) complete the form to create a new user
3) click on register and get redirected to the `/login?auth_callback=1` route in our application
4) the keycloak express middleware kick in and calls the accessDenied method, resulting in a 403 HTTP response

At this point, the user can go back to the home page of the application, and log in with the credentials they entered in 2). We implemented a custom `accessDenied` response to indicate to them that they can just log in if that issue occurs, working around the issue. This is however a less-than-ideal path to registration.

This behavior could not be reproduced consistently between users or between attempts: I managed to trigger the issue twice in a row from an application running in localhost, using the sso-dev keycloak instance, and then it did not do it again. Some of our users however have encountered the issue consistently (we tried deleting the user in the realm and make them register again, and the issue was reproducible for them).

The issue does not seem to occur when we clicking our "Login" button (which calls the `keycloak.connect()` middleware), and then clicking on the "Register" button from there, so this may have to do with routing the user directly to the registration page.

Note that we tried to add the `state` query string parameter in the "Register" redirection URL, as it is missing when we compare the URL in step (1) to the one that keycloak.connect() creates (the value for `state` was generated by the `UUID()` function from the keycloak nodejs adapter). However this did not solve the issue.

**Comment by wenzowski** [comment]
Network requests reproducing issue available as [har file](https://buttoninc.sharepoint.com/:u:/s/bc-cas2/EceZvKQXBVRGu8gxn2ttb6IBgoXuN8bDWTzMnvZ0djnr2A?e=Ls2l3c).

**Comment by ShellyXueHan** [comment]
Update from RedHat:
There is no specific configuration to replicate user registration cache, we will need to wait for the next release to have this added, which is still a date-to-be-determined. On the other side, as Alec has found a message from RedHat sometime ago about using the registration endpoint. This does not apply to this as we are running a stateless KeyCloak instance on Openshift, no sticky session is available to support. As a result, for now you will have to either go with the normal auth flow or use the custom accessDenied response you mentioned. And it's either that the next release has this available and we upgrade to include ot, or that this application has moved on to use an identity provider instead of keycloak local users as expected.

**Comment by brycereid73** [comment]
Waiting for SSO to include as a feature.

Plan is to move away from local users. IDP Users

**Comment by ShellyXueHan** [comment]
@brycereid73 here's the RedHat support ticket: https://access.redhat.com/support/cases/#/case/02713060 The team has follow up with some more options, please try out and provide feedback!

**Comment by zsamji** [comment]
@arcshiftsolutions  @junminahn is it still a thing we should add in our backlog?

**Comment by arcshiftsolutions** [comment]
@zsamji We haven't had any other teams ask about local users that I know. As noted our focus has been providing IDP access with our new shared realm approach. I think we can close this item and re-open if we have further requests.
