### ISSUE TITLE
Ability to filter users based on role mapping permission

### ISSUE THREAD

**Issue by kristimeredith** [bcgov/ocp-sso#8]
We are onboarding hundreds of users. I would be great to be able to differentiate between users that have already been granted a particular role mapping vs people that have not yet been granted access. 

I have been having to go through the list periodically and clicking through each individual user to ensure that no one has been missed.

**Comment by cvarjao** [comment]
@kristimeredith, you can get a developer to use keycloak API for more advanced queries. You can also go to the role and see the list of users assigned to that role. We are not looking into enhance/customize Keycloak UI.
