### ISSUE TITLE
Update storage documentation from hot backup to cold

### ISSUE THREAD

**Issue by caggles** [bcgov/ocp-sso#80]
Referring to https://github.com/bcgov/ocp-sso/wiki/2.4-Increase-storage-for-statefulset

This documentation includes a step where you take a tar of the datafiles while the database is still running. This is not an effective method of backing up a database.

There are two options for replacing this:

1. Update it to recommend the use of pgdump as the backup instead.
2. Update it to recommend scaling down the patroni stateful set _before_ taking the tar of the datafiles.

**Comment by ShellyXueHan** [comment]
Document is in the repo's wiki. So I updated it directly: https://github.com/bcgov/ocp-sso/wiki/2.4-Update-immutable-field-in-statefulset-with-DB-backup

feel free to update the content!

**Comment by ShellyXueHan** [comment]
@caggles @jefkel here's the updated steps/wiki on how to take DB backup and restore: https://github.com/bcgov/ocp-sso/wiki/2.4-Update-immutable-field-in-statefulset-with-DB-backup As I can't start a PR for wiki pages, feel free to update it directly when needed.
