### ISSUE TITLE
How users are linked?

### ISSUE THREAD

**Issue by cvarjao** [bcgov/ocp-sso#83]
For SAML identity providers (IDIR, BCeID), users are linked using the SAML `Response/Subject/NameId` which is configured to return the user GUID without dashes also known as `useridentifier`.
Example of a relevant SAML response fragment?
```
<Response xmlns="urn:oasis:names:tc:SAML:2.0:protocol"
          Version="2.0"
          >
    <ns2:Assertion xmlns:ns2="urn:oasis:names:tc:SAML:2.0:assertion"
                   Version="2.0"
                   >
        <ns2:Subject>
            <ns2:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent">USER-GUID-GOES-HERE</ns2:NameID>
        </ns2:Subject>
    </ns2:Assertion>
</Response>
```

**Comment by zsamji** [comment]
closing and captured here https://github.com/bcgov/sso-keycloak/discussions/69
