### ISSUE TITLE
Intermittent SSO issues:

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/ocp-sso#86]
## What is the ticket for? 

To track instances of intermittent issues that are difficult or impossible to reproduce. 

## Why?

If we track the date, duration, severity of these intermittent issues it will provide better insight on the type of operational work we can schedule to mitigate them

--- DO NOT DELETE, COPY & PASTE TEMPLATE BELOW ---

Summary:
**Date** (including time):
**Approximate Duration of issue**:
**Did the issue resolve itself?**:
**Impact/Severity**: 
**Extra Notes**:
**Paste relevant logs below** (please do not post anything sensitive 😅  ):
**Resolution**: tickets/PR/notes on how issue was fixed

**Comment by ShellyXueHan** [comment]
**Summary**: Patroni connection timeouts
**Date** (including time): Oct 15 2020 9:30 AM
**Approximate Duration of issue**: ~15 mins
**Did the issue resolve itself?**: no, manually restarted the issue pod
**Impact/Severity**: on Production SSO. Some tenants of SSO were not able to have their clients authenticate during this period. This disrupted their workflow.
**Extra Notes**: ETCD peaks
**Paste relevant logs below** (please do not post anything sensitive 😅  ): same API timeout logs

**Comment by ShellyXueHan** [comment]
**Summary**: Unhealthy Node cause db pod to hang
**Date** (including time): Oct 15 2020 4:30 AM
**Approximate Duration of issue**: ~30 mins
**Did the issue resolve itself?**: no. patroni was able to failover, but there are still connection hanging with the issue db pod
**Impact/Severity**: on Dev SSO. Some tenants of SSO were not able to have their clients authenticate during this period.
**Extra Notes**: unhealthy node
**Paste relevant logs below** (please do not post anything sensitive 😅  ): network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized]

**Comment by ShellyXueHan** [comment]
**Summary**: gluster storage issue caused all SSO instance DB to fail
**Date** (including time): Oct 8 2020 6:30 AM
**Approximate Duration of issue**: ~2 hours
**Did the issue resolve itself?**: no. manual restart was needed
**Impact/Severity**: dev/test/prod SSO all affected. service unavailable for >=2 hours
**Extra Notes**: 
**Paste relevant logs below** (please do not post anything sensitive 😅  ):

**Comment by ShellyXueHan** [comment]
@patricksimonian can you fill in this one? I wasn't there during this so have no better info about it...

**Summary**: SSO pod OOM kill
**Date** (including time): ?
**Approximate Duration of issue**: ?
**Did the issue resolve itself?**: ?
**Impact/Severity**: ?
**Extra Notes**: 
**Paste relevant logs below** (please do not post anything sensitive 😅  ):

**Comment by patricksimonian** [comment]
> **Summary**: gluster storage issue caused all SSO instance DB to fail
> **Date** (including time): Oct 8 2020 6:30 AM
> **Approximate Duration of issue**: ~2 hours
> **Did the issue resolve itself?**: no. manual restart was needed
> **Impact/Severity**: dev/test/prod SSO all affected. service unavailable for >=2 hours
> **Extra Notes**:
> **Paste relevant logs below** (please do not post anything sensitive 😅 ):

**Comment by ShellyXueHan** [comment]
**Summary**: SSO pod CPU spike and kill
**Date** (including time): Nov 27th 2020 11:00 AM
**Approximate Duration of issue**:  ~ 40 mins (pods get into stable status around 11:40)
**Did the issue resolve itself?**: it did
**Impact/Severity**: Significant impact on PRODUCTION sso with all IDP logins, seemed to be the same issue happened a week ago
**Extra Notes**: currently have a RedHat ticket open: https://access.redhat.com/support/cases/#/case/02808261
**Paste relevant logs below** (please do not post anything sensitive 😅  ): details in redhat ticket

**Comment by arcshiftsolutions** [comment]
**Summary:** SSO pod CPU spike and kill
**Date (including time):** Nov 20th 2020 3:40 PM
**Approximate Duration of issue:** ~ 40 mins (pods returned to stable status around 4:20)
**Did the issue resolve itself?:** Yes
**Impact/Severity:** Significant impact on PRODUCTION sso with all IDP logins
**Extra Notes:** Currently the team has a RedHat ticket open: https://access.redhat.com/support/cases/#/case/02808261
**Paste relevant logs below (please do not post anything sensitive 😅 ):** Details are in the Redhat ticket

**Comment by brycereid73** [comment]
Shelly suggests closing if we don't need the record.
