### ISSUE TITLE
Setup monitoring for KeyCloak SSO in uptime robot

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/ocp-sso#87]
As the KeyCloak SSO Support team member, I need to monitor the uptime and response of the KeyCloak SSO. One tool that can help accomplish that is https://uptimerobot.com/ (it has a free version). I need to find an API endpoint(s) that are representative of the KeyCloak SSO availability and monitor the endpoints with the uptime robot.

**Comment by zsamji** [comment]
niran completed this @arcshiftsolutions let me know if i'm wrong

**Comment by ShellyXueHan** [comment]
@zsamji we've added prod SSO in our platform status page: https://status.developer.gov.bc.ca/ But dev and test SSO are not included. Would you like to have a separate status page for SSO only?

**Comment by zsamji** [comment]
@ShellyXueHan yes a separate page would be super helpful. thanks in advance

**Comment by ShellyXueHan** [comment]
https://stats.uptimerobot.com/m8VZBU5QBW
