### ISSUE TITLE
Profile SSO-Prod historical app utilization 

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#91]
### Background:
We would like to gather historical resource usage detail from the Production SSO deployment to better target the resource requests/limits for both the front end application deployment, and the postgres DB.

### Tasks:
- capture SSO app pod daily resource consumption pattern (check sysdig for historical consumption metrics)
- capture prod SSO DB daily resource consumption metrics (check sysdig for historical consumption metrics)
- Document average/Peak resource targets for each component after reviewing historical metrics

**Comment by patricksimonian** [comment]
whats the end point for sysdig :O

**Comment by patricksimonian** [comment]
we should ask Redhat for guidance on the best way to load test KC

**Comment by patricksimonian** [comment]
sysdig dashboard updated for SSO prod to demonstrate avg & max cpu/memory utilization for postgres and keycloak pods
