### ISSUE TITLE
SSO Epic - Resource Tuning of Application Pods

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#92]
### Background:
We had OOM with some sso app pods during the past weeks. During debugging we found out that the sso deployment resource request/limits can be improved. We will need to investigate recommended resource requirements and internal JVM settings for sso pods and to implement the changes with minimum impact.

### Value add:
- improve sso performance, reduce chance of out of resource issues

### Epic Tasks:
- profile sso app utilization under load
- determine proper resource level and update sso deployments

**Comment by zsamji** [comment]
havent heard this is an issue @arcshiftsolutions you ok for me to remove?

**Comment by arcshiftsolutions** [comment]
@zsamji - This one is fine to close with all the tuning we've done. 👍
