### ISSUE TITLE
SSO Epic - Operational Impact Testing

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#93]
### Background:
To improve the operation of the SSO Service, we would like to understand the impact on application/users during operational activities.  Creating automated tests to both simulate load, and identify impact of operational maintenance to the service will improve the teams ability to predict the impacts of operational updates.

### Value add:
- be able to load test SSO for service expectations
- Better predict impact of regular maintenance activities

### Epic Tasks:
- create load testing automation for sso
- Test SSO application impact during redeployments under load (i.e.: cache replications among pods)
- Test SSO application impact during database fail-over events under load

**Comment by zsamji** [comment]
will address in this in our current processes
