### ISSUE TITLE
SSO application pod impact during redeployments

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#95]
### Background:
Understand what are the impacts on SSO application pods during a redeployment.

### Tasks:
- verify cache replication on new pods
- verify DB transaction cancellation during pod shutdown
- identify other relevant events
- document client behavior during a redeployment (errors/timouts/etc? in the load test tool)

**Comment by ShellyXueHan** [comment]
Here's a prep PR for this task: https://github.com/bcgov/ocp-sso/pull/101

**Comment by patricksimonian** [comment]
I'm still unsure if we can do a rolling deployment but we can simulate a recreate deployment by scaling from 0 back to n pods. I've done this and ran the test as soon as one pod is available.

results are:
```sh
==========================================
Finding max, median, average, and minimums
==========================================

Statistics for ::Client APIs::Get clients http request duration

max: 752.825653
min: 19.140172
avg: 234.07985359999998
med: 193.152612

Statistics for ::Client APIs::Create clients http request duration

max: 1611.240773
min: 355.153531
avg: 860.51858715
med: 853.836879

Statistics for ::Client APIs::Delete clients http request duration

max: 2453.321228
min: 948.455439
avg: 1583.82126615
med: 1577.487647
```

**Comment by patricksimonian** [comment]
based on these results it does look like there is a signiicant impact to the k6 service during its redeployment. In general it looks like service response/request times are impacted by an increase of atleast 2x. Based on 
CPU: 500 millicores to 1 core and
Memory: 1 GiB to 1 GiB
per pod

**Comment by patricksimonian** [comment]
During a redeployment it looks like caches are syncing up correctly. I could write a script that looks at the log stream looking for the `Finished rebalance with members` statement but i'd rather see if theres a tool out there. Opened a support case for this https://access.redhat.com/support/cases/#/case/02796701.

**Comment by patricksimonian** [comment]
Transaction query: `SELECT locktype, database, state, query FROM pg_locks pl LEFT JOIN pg_stat_activity psa ON pl.pid = psa.pid;`

**Comment by patricksimonian** [comment]
still trying to figuire out the best way to implement it. The query itself creates transactions which are hard to filter

**Comment by ShellyXueHan** [comment]
For running the test, here's an idea to leverage the BCDK utils and prod DB backup/restore:
So for any changes we'll be introducing to sso, let's start the PR that spins up a sandbox instance with original settings. Then as we create operational change, run bcdk locally to apply it to the sandbox instance while running the test cases to collect results. In addition, we should also have a DB taken from prod instance for simulation. Ideally we should be able to run tests on dev/test/prod, so we would have the test prerequisite setup already. Thus a DB restore would have set us up with running tests in sandbox as well.

**Comment by patricksimonian** [comment]
sounds great. Another thought I had was for us to run the tests as soon as a recreate deployment has been triggered. We can run the tests for a longer time frame ( > 2 min) to get a better idea of when the pods become responsive as well.

**Comment by patricksimonian** [comment]
Closed with no changes implemented to a cluster. This issue was for info gathering.
