### ISSUE TITLE
SSO user impact during operational tasks

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#96]
### Background:
Have an estimation on what type of impacts will be cause from different SSO operational tasks

### Tasks:
- verify SSO service behaviour and user impact during maintenance time

## Definition of Done
- document average service interruption/disrruption during sso deployment / db update / etc.
- communicate SSO service expectations

**Comment by patricksimonian** [comment]
Baseline Metrics from testing:

## Creating Clients request/response duration
- max: 661.505842ms
- avg: 267.39357975
- median: 281.688532
## Get Clients request/response duration
- max: 2303.84578
- avg: 835.1800834285713
- median: 479.559737
## Delete Clients request/response duration
- max: 804.036669
- avg: 468.2662060666667
- median: 413.092443

**Comment by ShellyXueHan** [comment]
Update:
Running test cases in different identified scenarios. As for now, due to time limit, we will be only running once for each case and compare to baseline. Will need to have a plan to run in more differnet time period and over longer span.

Results tracked here: https://github.com/bcgov/ocp-sso/issues/109
