### ISSUE TITLE
Spike: Identify if JVM 'heap allocation' is appropriate based on our required memory request/limits 

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/ocp-sso#97]
> helpful doc on JVM tuning https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.3/html/getting_started_with_jboss_eap_for_openshift_container_platform/configuring_eap_openshift_image#jvm-memory-configuration_default

Work with RedHat (after we discover what our ideal memory allocation is per pod) to see if there is any further tuning that is required from our Keycloak instance. 

## To Do
- investigate JVM garbage collection process to see if its healthy
- see if there is any further configuration required (check link above)

**Comment by patricksimonian** [comment]
@mitovskaol do you know any more details on the engagement we are going to have with Redhat for Keycloak with regard to tuning our application?

**Comment by mitovskaol** [comment]
@patricksimonian  We are still waiting for their proposal outlining details of their engagement with us i.e. what exactly they will be assessing in our KeyCloak implementation. They promised to get it in by the end of this week and in this case, we hope to have their SSO architect start late next week. It is going to be a 2 week engagement.

**Comment by patricksimonian** [comment]
We got some great information based on metrics from Sysdig, and our redhat support case. There is significant evidence that our JVM heap allocation and its GC is not optomized for the current cpu/memory requests. 

Recommendations have been made in the support case
