### ISSUE TITLE
SSO: Load testing Plan

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/ocp-sso#98]
After identifying what load testing tool we are going to use, we should create a plan of what/how we are testing the Keycloak service. 

## To Do
- confer with Redhat to see what are the best ways to load test
- document a plan of what we are load testing

## Definition of Done
- a document in the keycloak-admin repo with our load test plan :)

**Comment by patricksimonian** [comment]
waiting for Matt to get back to me

**Comment by patricksimonian** [comment]
received a helpful link on keycloak's performance testing suite https://github.com/keycloak/keycloak/tree/master/testsuite/performance

**Comment by patricksimonian** [comment]
# Summary
 Our primary goal with the Load Testing Plan is to actual functionally test our redhat sso service. This functional test will provide quantitative metrics that are surfaceable by a normalized means (such as JSON) so that we can internally check the health of our redhat sso service and react to it when it goes out of spec. In addition we are looking for a means to check the health of the redhat sso service from the end users perspective (like testing against a health check end point). 

## Technologies
There are a few technologies that we can use seperately or in tandem to accomplish our internal check. 

### k6
 K6 is perfect for use against the Keycloak API. With this we can test common functionalities that users of the redhat service may interact with. Our initial flow would be:
   - k6 creates a new client
   - k6 creates users 
   - k6 users authenticate
   - k6 users authorize
    - k6 users refresh
   - k6 deletes client 

This flow can also be run concurrently to simulate load. 

The process of the tests could be:
k6 tests run > output json > json is pushed to prometheus > sysdig picks up json > sysdig alerts us if results are out of spec

#### Drawbacks

K6 does not run in a browser. We will unable to test end user flows from the browser. Such as accomplish an authentication flow via siteminder or github

## Cypress E2E Testing

Cypress will allow us to test the end user flow from the browser. This will help us catch errors that were born from config changes to our IDPs. For example if there are changes to the idir idp. 

An example test flow could be:
   -> a user navigates to a sample app that is well integrated with keycloak
   -> user attempts to login via idir 
   -> user does a page refresh
   -> user  waits (for access token to expire) and tries to do an authenticated action
  -> user quits session and logs back in
  -> etc you get the point

similiarly the CI flow could be: run cypress tests > capture output in a standardized format > push to prometheus > surface in sysdig

**Comment by patricksimonian** [comment]
@jefkel what do you think?

**Comment by ShellyXueHan** [comment]
Some thoughts from SRE course: in k6 test cases, we are now targeting at service availability as MVP. Next part of planning can include service latency and service quality that as a whole is helpful for defining SLIs, for example plan on enhancement of test cases with checking response time, error handling and etc. during operational actions.

**Comment by patricksimonian** [comment]
I think response times come out of the box from any k6 test case. It shows latency between requests/responses
