### ISSUE TITLE
SSO: Create Load Testing cases

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/ocp-sso#99]
## To do
- implement load test cases based on the guidance from the load testing plan

## Definition of Done
- a set of load test cases that are runnable

**Comment by ShellyXueHan** [comment]
Update:
- functional test cases create as of https://github.com/bcgov/ocp-sso/pull/103

**Comment by ShellyXueHan** [comment]
MVP test cases created and tested. Will continue to improve and create more. Closing this ticket.
